# API 명세 단일 출처 — 문서(README), 프론트 API 클라이언트(endpoints.js), 목업 서버(mock.js)가 모두 여기서 만들어짐
SID = 'ses_7K2X9'

USER = {"id": "usr_001", "email": "hyeongwon@example.com", "nickname": "노형원", "avatarUrl": None, "plan": "FREE"}

# auth 값: none(누구나) · member(로그인 회원) · participant(이 세션에 입장한 회원) · host(이 세션 진행자) · leader(팀장 = 배치를 확정하는 참가자 1명)
# 게스트 입장은 없음 — 회원가입 + 로그인 + 프로필 작성이 끝나야 방에 들어갈 수 있다.
AUTH_LABEL = {'none': '필요 없음', 'member': '회원 토큰', 'participant': '세션 참가자 (회원)', 'host': '세션 진행자만', 'leader': '팀장만 (참가자 중 1명)'}
CODE = '7K2X9M'   # 방 코드 = 대문자·숫자 6자리 (초대 링크도 /s/{방 코드})

E = []
def ep(id, method, path, auth, title, desc, req=None, res=None, errors=(), notes=(), query=None, status=200):
    E.append(dict(id=id, method=method, path=path, auth=auth, title=title, desc=desc, req=req, res=res,
                  errors=list(errors), notes=list(notes), query=query, status=status))

# ───────── 계정 · 인증 ─────────
ep('auth.signup', 'POST', '/auth/signup', 'none', '이메일 회원가입',
   '이메일·비밀번호·닉네임과 약관 동의로 계정을 만들고 바로 로그인 상태로 만든다.',
   req={"email": "hyeongwon@example.com", "password": "********", "nickname": "노형원",
        "agreements": {"terms": True, "privacy": True, "marketing": False}},
   res={"user": USER, "accessToken": "eyJhbGciOi...", "expiresIn": 3600}, status=201,
   errors=[('EMAIL_TAKEN', 409, '이미 가입된 이메일'), ('VALIDATION', 400, '비밀번호 8자 미만 · 필수 약관 미동의 등')],
   notes=['비밀번호는 bcrypt/argon2로 해시해서 저장한다(원문 저장 금지).',
          '약관 동의는 버전과 동의 시각을 함께 기록한다(나중에 약관이 바뀌면 다시 동의받기 위해).',
          '리프레시 토큰은 httpOnly 쿠키로 내려주는 것을 권장한다.'])
ep('auth.login', 'POST', '/auth/login', 'none', '이메일 로그인', '이메일과 비밀번호를 확인하고 토큰을 준다.',
   req={"email": "hyeongwon@example.com", "password": "********", "remember": True},
   res={"user": USER, "accessToken": "eyJhbGciOi...", "expiresIn": 3600},
   errors=[('INVALID_CREDENTIALS', 401, '이메일 또는 비밀번호가 틀림'), ('TOO_MANY_ATTEMPTS', 429, '연속 실패 제한')],
   notes=['응답 본문에는 액세스 토큰(짧게, 예: 1시간)만. 리프레시 토큰은 Set-Cookie로 내려준다 → auth.refresh 참고.',
          'remember=true면 리프레시 쿠키를 30일 유지(Max-Age), false면 Max-Age 없이(브라우저를 닫으면 사라짐).'])
ep('auth.refresh', 'POST', '/auth/refresh', 'none', '로그인 유지 (액세스 토큰 새로 받기)',
   '액세스 토큰이 만료됐거나 앱을 다시 열었을 때, 쿠키에 있는 리프레시 토큰으로 새 액세스 토큰을 받는다. 본문은 보내지 않는다(쿠키로 인증).',
   req=None,
   res={"user": USER, "accessToken": "eyJhbGciOi...", "expiresIn": 3600},
   errors=[('REFRESH_INVALID', 401, '리프레시 토큰이 없음 · 만료 · 로그아웃됨 · 이미 사용됨 → 다시 로그인')],
   notes=['리프레시 쿠키 설정: HttpOnly · Secure · SameSite=Lax · Path=/api/v1/auth. 자바스크립트에서 읽을 수 없게.',
          '회전(rotation): 쓸 때마다 새 리프레시 토큰으로 바꿔서 Set-Cookie 하고, 이전 토큰은 무효로 만든다.',
          '이미 쓴(무효가 된) 리프레시 토큰이 다시 들어오면 탈취로 보고 그 사용자의 리프레시 토큰을 전부 무효화한다.',
          '로그인할 때 받은 remember 값을 리프레시 토큰에 저장해 두고, 회전할 때도 같은 유지 기간을 적용한다.',
          '프론트 동작: API가 401을 받으면 이 API를 한 번 부르고 성공하면 원래 요청을 다시 보낸다. 실패하면 로그인 화면으로.'])
ep('auth.oauth', 'POST', '/auth/oauth/{provider}', 'none', '소셜 로그인 (google · kakao)',
   '소셜 로그인 창에서 받은 code를 서버가 소셜 서버에 확인하고, 처음이면 계정을 만든다.',
   req={"code": "소셜_인가_코드", "redirectUri": "https://ideationengine.app/oauth/callback", "remember": True,
        "agreements": {"terms": True, "privacy": True, "marketing": False}},
   res={"user": USER, "accessToken": "eyJhbGciOi...", "isNewUser": False},
   errors=[('OAUTH_FAILED', 400, '소셜 서버 확인 실패 · 이메일 제공에 동의하지 않음'), ('AGREEMENT_REQUIRED', 409, '처음 가입인데 필수 약관(terms · privacy) 동의가 없음'),
           ('EMAIL_TAKEN', 409, '같은 이메일로 이미 가입된 계정이 있는데 이 소셜 계정은 연결 안 됨 → 로그인 후 계정 설정에서 연결'),
           ('VALIDATION', 400, 'provider가 google · kakao가 아님')],
   notes=['isNewUser=true면 프론트는 3번(프로필 만들기)으로 보낸다.',
          '토큰은 이메일 로그인과 같게: 본문에 액세스 토큰, 리프레시 토큰은 쿠키 (remember 규칙도 같음).',
          'agreements는 처음 가입일 때만 필요하다 (이미 있는 계정이면 무시). 가입 때처럼 약관 버전과 동의 시각을 기록.',
          '이메일이 같다는 이유만으로 기존 계정에 자동으로 연결하지 않는다 (남의 계정을 가로채는 것 방지). 연결은 로그인한 뒤 account.connect로만.'])
ep('auth.logout', 'POST', '/auth/logout', 'none', '로그아웃',
   '쿠키의 리프레시 토큰을 무효화하고 쿠키를 지운다(Set-Cookie Max-Age=0).', res=None, status=204,
   notes=['액세스 토큰이 이미 만료된 상태에서도 로그아웃은 성공해야 한다(쿠키 기준으로 처리). 토큰이 없어도 204.'])
ep('auth.passwordReset', 'POST', '/auth/password/reset', 'none', '비밀번호 찾기 메일 보내기',
   '가입된 이메일이면 재설정 링크를 메일로 보낸다. 가입 여부를 노출하지 않도록 항상 같은 응답.',
   req={"email": "hyeongwon@example.com"}, res={"sent": True},
   errors=[('TOO_MANY_ATTEMPTS', 429, '같은 IP에서 10분에 5번 넘게')],
   notes=['가입된 이메일이든 아니든 응답은 똑같이 {"sent": true}. 메일은 가입된 이메일에만 보낸다.',
          '메일의 링크: https://ideationengine.app/reset-password?token=… (30분 · 한 번만 쓸 수 있는 토큰). 링크를 연 뒤 새 비밀번호를 정하는 화면 · API는 디자인 후 추가.',
          '비밀번호가 없는 소셜 전용 계정이면 "Google/카카오로 가입한 계정이에요" 안내 메일을 보낸다.'])
ep('auth.me', 'GET', '/me', 'member', '내 계정 요약',
   '오른쪽 위 프로필 버튼·팝오버에 필요한 정보(이름·이메일·요금제·프로필 요약·지난 세션 수).',
   res={"user": USER, "profileComplete": True,
        "profileSummary": {"desiredRole": "개발·구현", "skills": ["프론트엔드", "백엔드", "발표·피칭"]},
        "sessionCount": 6,
        "activeSession": {"sessionId": SID, "code": CODE, "topic": "교내 해커톤에서 만들 서비스 아이디어 정하기", "role": "host",
                          "status": "running", "stage": {"id": "diverge.vote", "label": "아이디어 발산", "subStep": 5, "progress": 55}}},
   errors=[('UNAUTHORIZED', 401, '액세스 토큰 없음·만료 → 프론트가 auth.refresh 후 다시 시도')],
   notes=['profileComplete: 닉네임·맡고 싶은 역할·스킬 1개 이상이 있으면 true. false면 profileSummary는 null.',
          'activeSession: 내가 참가 중인데 아직 끝나지 않은(lobby 또는 running) 세션. 없으면 null. 여러 개면 가장 최근 1개. 랜딩에서 "세션으로 돌아가기"(재접속)에 쓴다.',
          '내보내진(kicked) 세션은 activeSession에 넣지 않는다.'])
ep('legal.get', 'GET', '/legal/{type}', 'none', '약관 원문 (terms · privacy)',
   '회원가입 화면의 "보기" 팝업 내용. 법률 검토된 문서를 버전별로 관리한다.',
   res={"type": "terms", "version": "2026-09-01", "title": "이용약관", "html": "<h5>제1조 (목적)</h5><p>…</p>"},
   errors=[('NOT_FOUND', 404, 'terms · privacy가 아닌 type')],
   notes=['지금 시행 중인 최신 버전을 준다. 회원가입(auth.signup · auth.oauth) 때 이 version을 동의 기록에 남긴다.',
          '프론트가 html을 그대로 팝업에 넣으므로 관리자만 올리고, script 태그 · on… 속성처럼 실행되는 내용은 저장할 때 걸러낸다.'])

# ───────── 프로필 ─────────
ep('meta.skills', 'GET', '/meta/skills', 'none', '역할·스킬 목록',
   '프로필 화면의 칩 목록. 서버에서 내려주면 앱을 다시 배포하지 않고 스킬을 추가할 수 있다.',
   res={"roles": ["자료조사", "발표·기획", "문서정리", "개발·구현", "디자인"],
        "skillGroups": [{"id": "dev", "title": "개발", "hint": None, "skills": ["프론트엔드", "백엔드", "데이터", "인프라", "AI/ML"]},
                        {"id": "design", "title": "디자인", "hint": "만드는 결과물 기준", "skills": ["PPT 디자인", "웹 디자인", "앱 디자인", "영상·모션", "브랜딩·그래픽"]},
                        {"id": "plan", "title": "기획", "hint": "무엇을 설계하는 기획인지 기준", "skills": ["비즈니스 모델 기획", "기술 설계 기획", "서비스 기획", "프로젝트 관리", "사업계획서·제안서"]},
                        {"id": "etc", "title": "발표·기타", "hint": None, "skills": ["발표·피칭", "마케팅·홍보", "리서치·사용자 조사", "문서 정리", "논문"]}]})
PROFILE = {"nickname": "노형원", "strength": "발표 자료를 빠르게 잘 만들어요", "desiredRole": "개발·구현",
           "skills": ["프론트엔드", "백엔드", "PPT 디자인", "기술 설계 기획", "발표·피칭"], "avatarUrl": None, "updatedAt": "2026-09-12T10:20:00+09:00"}
ep('profile.get', 'GET', '/me/profile', 'member', '내 프로필 불러오기', '프로필 수정 화면을 채운다.', res=PROFILE,
   notes=['프로필을 아직 안 만들었으면 nickname은 가입 때 닉네임, strength · desiredRole · updatedAt은 null, skills는 [] (null 아님 — 화면이 배열로 씀).'])
ep('profile.update', 'PUT', '/me/profile', 'member', '내 프로필 저장',
   '닉네임·한 줄 강점·맡고 싶은 역할·할 수 있는 스킬을 저장한다. 진행 중인 세션에는 반영하지 않고 다음 세션부터 쓴다.',
   req={"nickname": "노형원", "strength": "발표 자료를 빠르게 잘 만들어요", "desiredRole": "개발·구현",
        "skills": ["프론트엔드", "백엔드", "PPT 디자인", "기술 설계 기획", "발표·피칭"]},
   res=PROFILE, errors=[('VALIDATION', 400, '닉네임 비어 있음 · 목록에 없는 스킬')],
   notes=['세션에 들어갈 때 이 프로필을 "스냅샷"으로 복사해 둔다. 그래야 세션 중에 프로필을 바꿔도 AI 판단이 흔들리지 않는다.'])
ep('profile.avatarUpload', 'POST', '/me/avatar', 'member', '프로필 사진 올리기',
   'multipart/form-data의 file 필드. 5MB 이하 이미지, 서버에서 정사각형으로 줄여 저장.',
   req="multipart/form-data · file=<이미지>", res={"avatarUrl": "https://cdn.ideationengine.app/avatars/usr_001.webp"},
   errors=[('VALIDATION', 400, '파일 없음 · 5MB 초과 · JPG/PNG/WebP 이미지가 아님')],
   notes=['가운데를 기준으로 정사각형으로 잘라 512×512로 줄여 저장. 파일 이름은 매번 새로 (브라우저 캐시 때문에 같은 주소 재사용 금지).',
          '예전 사진 파일은 지운다. 이후 auth.me · profile.get의 avatarUrl이 새 주소.',
          '5MB 검사는 프론트도 하지만 서버가 최종 판단.'])
ep('profile.avatarDelete', 'DELETE', '/me/avatar', 'member', '프로필 사진 삭제', '사진이 없으면 닉네임 첫 글자로 표시된다.', status=204,
   notes=['사진이 없어도 204 (같은 결과).'])

# ───────── 지난 세션 · 설정 · 요금제 ─────────
ep('history.list', 'GET', '/me/sessions', 'member', '지난 세션 기록',
   '내가 진행했거나 참여한 세션 목록. 역할 필터·주제 검색·커서 페이지네이션.',
   query={"role": "all · host · participant", "q": "검색어(주제)", "cursor": "다음 페이지 커서", "limit": 20},
   res={"counts": {"all": 6, "host": 3, "participant": 3},
        "items": [{"sessionId": "ses_7K2X9", "date": "2026-09-15", "topic": "교내 해커톤에서 만들 서비스 아이디어", "myRole": "host", "memberCount": 4, "durationMin": 30, "decidedTopic": "첫 회의 돕기", "reportAvailable": True},
                  {"sessionId": "ses_Q8M21", "date": "2026-08-27", "topic": "동아리 홍보 영상 기획", "myRole": "participant", "memberCount": 6, "durationMin": 17, "decidedTopic": None, "endedEarly": True, "reportAvailable": False}],
        "nextCursor": None},
   errors=[('VALIDATION', 400, 'role이 all · host · participant가 아님 · limit이 1~50 밖 · 알 수 없는 cursor')],
   notes=['넣는 세션: 내가 진행자였거나 참가자였던 세션 중 **시작한 세션**(진행 중 포함). 시작하지 않은 대기실 세션 · 내보내진 세션은 넣지 않는다.',
          '순서: 시작 시각 최신순. date = 시작한 날짜. durationMin = 실제로 진행한 분(진행 중이면 지금까지).',
          'decidedTopic = 주제 확정(topic.confirm)한 아이디어 제목, 없으면 null. endedEarly = 끝났는데 확정이 없음. reportAvailable = 보고서(9-2)가 있음 (9-2 전까지는 false).',
          'q = 세션 주제 부분 일치(대소문자 무시). counts는 q를 적용하고 role 필터는 적용하지 않은 개수.',
          'limit 기본 20, 최대 50.'])
SETTINGS = {"email": "hyeongwon@example.com", "passwordChangedAt": "2026-06-10T09:00:00+09:00",
            "connections": {"google": True, "kakao": False},
            "notifications": {"sessionInvite": True, "reportReady": True, "marketing": False}}
ep('settings.get', 'GET', '/me/settings', 'member', '계정 설정 불러오기', '로그인 정보·연결된 소셜 계정·알림 설정.', res=SETTINGS,
   notes=['비밀번호가 없는 소셜 전용 계정은 passwordChangedAt = null.'])
ep('settings.update', 'PATCH', '/me/settings', 'member', '알림 설정 바꾸기', '바뀐 항목만 보낸다.',
   req={"notifications": {"marketing": True}}, res=SETTINGS,
   errors=[('VALIDATION', 400, 'notifications 밖의 항목 · sessionInvite · reportReady · marketing이 아닌 키 · true/false가 아님')],
   notes=['보낸 키만 바꾸고, 바꾼 뒤 전체 설정을 돌려준다.'])
ep('account.changeEmail', 'PATCH', '/me/email', 'member', '이메일 바꾸기', '새 이메일로 확인 메일을 보내고, 링크를 눌러야 바뀐다.',
   req={"newEmail": "new@example.com", "password": "********"}, res={"verificationSent": True},
   errors=[('PASSWORD_MISMATCH', 403, '비밀번호가 틀림'), ('EMAIL_TAKEN', 409, '이미 다른 계정이 쓰는 이메일'),
           ('VALIDATION', 400, '이메일 형식이 아님 · 지금 이메일과 같음 · 비밀번호가 없는 소셜 전용 계정')],
   notes=['새 주소로 확인 메일: https://ideationengine.app/verify-email?token=… (24시간 · 한 번만). 링크를 누르기 전까지 이메일은 그대로.',
          '링크를 연 뒤 확정하는 화면 · API는 디자인 후 추가. 예전 주소에는 "이메일 변경 요청이 있었어요" 안내 메일.',
          '비밀번호 확인 실패를 401로 주면 프론트가 로그인 유지(refresh) 후 같은 요청을 한 번 더 보내므로 403 PASSWORD_MISMATCH를 쓴다.'])
ep('account.changePassword', 'PATCH', '/me/password', 'member', '비밀번호 바꾸기', '현재 비밀번호 확인 후 변경, 다른 기기 로그인은 끊는다.',
   req={"currentPassword": "********", "newPassword": "********"}, res=None, status=204,
   errors=[('PASSWORD_MISMATCH', 403, '현재 비밀번호가 틀림'), ('VALIDATION', 400, '새 비밀번호 8자 미만')],
   notes=['지금 요청한 로그인(이 액세스 토큰을 발급한 리프레시 토큰 계열)은 유지하고, 그 사용자의 다른 리프레시 토큰은 모두 무효화한다 → 다른 기기는 액세스 토큰이 만료되면 로그인 화면으로.',
          '액세스 토큰에 로그인 계열 id를 넣어 두면 "지금 로그인"을 알 수 있다 (리프레시 쿠키는 Path=/api/v1/auth라 이 요청에는 오지 않음).',
          '비밀번호가 없는 소셜 전용 계정은 currentPassword 없이 새 비밀번호를 만들 수 있다. passwordChangedAt 갱신.'])
ep('account.connect', 'POST', '/me/connections/{provider}', 'member', '소셜 계정 연결', '로그인된 계정에 google/kakao를 연결한다.',
   req={"code": "소셜_인가_코드"}, res={"connections": {"google": True, "kakao": True}},
   errors=[('OAUTH_FAILED', 400, '소셜 서버 확인 실패'), ('OAUTH_TAKEN', 409, '그 소셜 계정이 이미 다른 계정에 연결됨')],
   notes=['소셜 계정의 이메일이 내 이메일과 달라도 연결할 수 있다 (로그인한 사람이 직접 연결하므로).', '이미 내 계정에 연결된 같은 소셜 계정이면 그대로 200.'])
ep('account.disconnect', 'DELETE', '/me/connections/{provider}', 'member', '소셜 계정 연결 해제',
   '비밀번호가 없는 계정에서 마지막 로그인 수단은 해제할 수 없다.', status=204, errors=[('LAST_LOGIN_METHOD', 409, '마지막 로그인 수단')],
   notes=['연결돼 있지 않아도 204 (같은 결과). 화면에는 아직 해제 버튼이 없다.'])
ep('account.withdraw', 'DELETE', '/me', 'member', '회원 탈퇴',
   '계정과 세션 기록을 지운다. 복구 불가. 다른 사람이 함께한 세션의 익명 댓글·아이디어는 "탈퇴한 사용자"로 남길지 정책 결정 필요.',
   req={"password": "********", "reason": "선택 입력"}, status=204,
   errors=[('PASSWORD_MISMATCH', 403, '비밀번호가 틀림')],
   notes=['비밀번호가 없는 소셜 전용 계정은 password 없이 탈퇴(로그인한 토큰으로 확인).',
          '지우는 것: 이메일 · 비밀번호 · 닉네임 · 프로필 · 사진 · 소셜 연결 · 설정 · 모든 리프레시 토큰, 응답에서 리프레시 쿠키도 지움(Max-Age=0).',
          '(임시 규칙 — 기획 결정 전) 다른 사람과 함께한 세션의 익명 아이디어 · 댓글 · 표는 남기고 계정 연결만 끊는다. 결과 · 기록에 주인 이름이 필요하면 "탈퇴한 사용자".',
          '같은 이메일로 다시 가입할 수 있다 (새 계정).'])
ep('billing.plan', 'GET', '/billing/plan', 'member', '현재 요금제와 한도',
   '프론트가 잠금(🔒PRO)을 그릴 때 쓰는 한도 값. 한도는 서버가 최종 판단한다.',
   res={"plan": "FREE", "limits": {"maxSessionMinutes": 30, "unlimitedDuration": False},
        "pro": {"priceLabel": "가격 미정", "features": ["30분 넘는 세션 (60분 · 90분 · 제한 없음)"]}},
   notes=['FREE: maxSessionMinutes 30 · unlimitedDuration false / PRO: maxSessionMinutes null · unlimitedDuration true.',
          'session.create의 403 PLAN_LIMIT 검사와 같은 값을 써야 한다 (한 곳에 두기).'])
ep('billing.checkout', 'POST', '/billing/checkout', 'member', 'Pro 결제 시작',
   '결제 대행사(PG) 결제창 주소를 만들어 돌려준다. 결제 완료는 PG → 서버 웹훅으로 확정한다(프론트 응답만 믿지 않기).',
   req={"plan": "PRO", "period": "monthly"}, res={"checkoutUrl": "https://pg.example.com/checkout/abc"},
   errors=[('ALREADY_PRO', 409, '이미 PRO'), ('VALIDATION', 400, 'plan이 PRO가 아님 · period가 monthly가 아님')],
   notes=['가격·PG사는 아직 미정. 웹훅 엔드포인트(POST /billing/webhook)도 함께 필요.',
          'PG를 정하기 전에는 PG 테스트 결제창(또는 서버의 임시 안내 페이지) 주소를 돌려준다. 요금제를 PRO로 바꾸는 건 웹훅을 받았을 때만.'])

# ───────── 세션 만들기 · 입장 · 대기실 ─────────
SESSION = {"sessionId": SID, "code": CODE, "inviteUrl": "https://ideationengine.app/s/" + CODE,
           "topic": "교내 해커톤에서 만들 서비스 아이디어 정하기", "criteria": None,
           "durationMin": 30, "maxMembers": 4, "status": "lobby",
           "stage": {"id": "lobby", "label": "대기실", "subStep": None, "progress": 0},
           "timer": {"endsAt": None, "remainingSec": None}, "host": {"participantId": "par_01", "nickname": "노형원"},
           "me": {"participantId": "par_01", "role": "host", "isLeader": False}, "memberCount": 3}
ep('session.create', 'POST', '/sessions', 'member', '세션 만들기',
   '주제·시간·인원으로 세션(방)을 만들고 방 코드와 초대 링크를 준다. 만든 사람이 진행자가 된다.',
   req={"topic": "교내 해커톤에서 만들 서비스 아이디어 정하기", "durationMin": 30, "maxMembers": 4, "criteria": "지역문제 · 심사=창의성/실현성"},
   res=SESSION, status=201,
   errors=[('PLAN_LIMIT', 403, '무료 회원이 30분 초과 또는 제한 없음(null) 선택'), ('PROFILE_REQUIRED', 409, '프로필을 아직 안 만듦'), ('VALIDATION', 400, '주제 비어 있음 · 인원 2~8 밖')],
   notes=['durationMin: 1~30(무료), 60·90 또는 null(=제한 없음)은 PRO만. 프론트에서 막아도 서버에서 꼭 다시 검사.',
          '방 코드: 대문자+숫자 6자리, 헷갈리는 글자(0 O 1 I L)는 빼고 만든다. 끝나지 않은 방끼리 겹치지 않게.',
          '초대 링크는 방 코드를 그대로 쓴다: https://ideationengine.app/s/{방 코드}. 별도 초대 토큰은 없다.',
          'maxMembers는 진행자 포함 인원.'])
ep('session.lookup', 'GET', '/sessions/lookup', 'member', '방 코드로 방 찾기',
   '입장하기 전에 방이 있는지, 들어갈 수 있는지 확인한다. 초대 링크(/s/{방 코드})로 온 경우도 코드로 찾는다.',
   query={"code": "방 코드 6자리 (대소문자 구분 없음)"},
   res={"sessionId": SID, "code": CODE, "topic": "교내 해커톤에서 만들 서비스 아이디어 정하기", "hostNickname": "노형원",
        "memberCount": 3, "maxMembers": 4, "status": "lobby", "alreadyJoined": False, "myRole": None},
   errors=[('SESSION_NOT_FOUND', 404, '없는 코드 · 끝난 방'), ('SESSION_FULL', 409, '인원 가득 (이미 참가 중인 사람은 제외)'),
           ('SESSION_STARTED', 409, '이미 시작한 방에 새로 들어오려 함 (이미 참가 중인 사람은 제외)'), ('KICKED', 403, '이 방에서 내보내진 사람')],
   notes=['alreadyJoined=true면 재접속이다. 그때는 방이 가득 찼거나 이미 시작했어도 에러를 주지 않는다. myRole은 그 사람의 역할(host/participant).',
          '코드 무차별 대입을 막기 위해 사용자·IP당 요청 횟수를 제한한다.'])
ep('session.join', 'POST', '/sessions/{sessionId}/join', 'member', '방에 들어가기 (처음 입장 · 재접속 모두)',
   '회원을 이 세션의 참가자로 등록한다. 이미 참가자라면 새로 만들지 않고 기존 참가 정보와 현재 단계를 돌려준다(재접속).',
   req={"code": CODE},
   res={"participantId": "par_02", "role": "participant", "rejoined": False,
        "session": {"status": "lobby", "stage": {"id": "lobby", "label": "대기실", "subStep": None, "progress": 0}}},
   errors=[('PROFILE_REQUIRED', 409, '프로필(닉네임·맡고 싶은 역할·스킬 1개 이상)이 없음 → 프론트가 프로필 만들기로 보냄'),
           ('SESSION_FULL', 409, '처음 입장인데 인원 가득'), ('SESSION_STARTED', 409, '처음 입장인데 이미 시작한 방'),
           ('KICKED', 403, '내보내진 사람'), ('SESSION_NOT_FOUND', 404, '코드가 이 세션과 다름 · 끝난 방')],
   notes=['게스트 입장은 없다. 회원 토큰이 없으면 401.',
          '처음 입장: 참가자를 만들고 계정 프로필을 이 세션용으로 복사(스냅샷)한 뒤, 대기실에 participant.joined 이벤트(닉네임 포함)를 보낸다.',
          '재접속(이미 참가자): 200 + rejoined=true + 현재 session.status·stage. 참가자를 새로 만들거나 participant.joined를 다시 보내지 않는다. 대신 접속 표시를 켜는 participant.online 이벤트만.',
          '진행자가 자기 방 코드로 들어와도 재접속으로 처리하고 role=host.',
          '같은 사람이 두 번 동시에 요청해도 참가자는 1명만 생기게(유니크 제약: session_id + user_id).',
          '인원 수 검사와 등록은 한 트랜잭션 안에서(마지막 자리에 두 명이 동시에 들어오는 경우).'])
ep('session.get', 'GET', '/sessions/{sessionId}', 'participant', '세션 상태',
   '모든 세션 화면의 상단바(단계 이름·전체 진행률·타이머·내 역할)를 채운다. 새로고침·재접속하면 이걸로 지금 있어야 할 화면을 정한다.',
   res=dict(SESSION, status="running", stage={"id": "diverge.vote", "label": "아이디어 발산", "subStep": 5, "progress": 55},
            timer={"endsAt": "2026-09-18T15:32:10+09:00", "remainingSec": 130}),
   errors=[('NOT_PARTICIPANT', 403, '이 세션 참가자가 아님 → 프론트가 방 코드 입장(2)으로'), ('KICKED', 403, '내보내진 사람')],
   notes=['me.isLeader: 파트 배치를 확정하는 <b>팀장</b>인지. 주제 확정(topic.confirm) 때 정해지고, 그 전에는 모두 false.',
          '프론트는 stage.id로 지금 있어야 할 화면을 정한다(team.assign 단계는 팀장이면 9-4, 나머지는 9-3).'])
ep('session.participants', 'GET', '/sessions/{sessionId}/participants', 'participant', '참여자 목록',
   '대기실의 참여자 줄. 이름·아바타·접속 여부만(스킬·답변 등은 포함하지 않음).',
   res={"maxMembers": 4, "items": [{"participantId": "par_01", "nickname": "노형원", "role": "host", "online": True, "isMe": True},
                                   {"participantId": "par_02", "nickname": "이세민", "role": "participant", "online": True},
                                   {"participantId": "par_03", "nickname": "김승희", "role": "participant", "online": True}]})
ep('session.kick', 'DELETE', '/sessions/{sessionId}/participants/{participantId}', 'host', '참여자 내보내기',
   '진행자가 대기실에서 잘못 들어온 사람을 내보낸다. 내보내진 사람에게 participant.kicked 이벤트.', status=204)
ep('session.start', 'POST', '/sessions/{sessionId}/start', 'host', '세션 시작',
   '입장을 닫고 타이머를 시작하고, 첫 단계(아이스브레이킹)를 연다. 모두에게 session.started 이벤트.',
   res={"status": "running", "stage": {"id": "icebreak", "label": "아이스브레이킹", "subStep": 1, "progress": 3},
        "timer": {"endsAt": "2026-09-18T15:30:00+09:00", "remainingSec": 1800}},
   errors=[('NOT_ENOUGH_MEMBERS', 409, '2명 미만'), ('FORBIDDEN', 403, '진행자가 아님')],
   notes=['시작 시점에 참여자 프로필 스냅샷을 확정하고, 뒤에서 AI 작업(최근 소식 검색 등)을 미리 돌리기 시작한다.'])
ep('session.advance', 'POST', '/sessions/{sessionId}/stage/next', 'host', '다음 단계로 넘기기',
   '진행자가 단계를 넘긴다. 서버가 다음 단계를 정해 stage.changed 이벤트를 모두에게 보낸다.',
   req={"from": "icebreak", "force": False}, res={"stage": {"id": "diverge.write", "label": "아이디어 발산", "subStep": 1, "progress": 25}},
   errors=[('STAGE_MISMATCH', 409, '이미 다른 단계로 넘어감(두 번 누름)'), ('STAGE_LOCKED', 409, '대기실(→ 세션 시작으로) · 투표 결과(→ 주제 확정으로)에서 넘기려 함 · AI 검증이 끝나기 전(ready=false) review → vote'),
           ('NOT_ALL_SUBMITTED', 409, 'diverge.write(아이디어) · diverge.comment(댓글)에서 아직 안 낸 사람이 있음. details {pendingCount, memberCount}. force=true면 넘어감'),
           ('PARTS_NOT_READY', 409, '파트 나누기 AI 작업이 아직 안 끝남(team.split에서 넘기려 할 때)')],
   notes=['req.from 으로 "내가 보고 있던 단계"를 보내서 중복 클릭·동시 클릭을 막는다.',
          '제출 단계는 전원이 내야 넘어간다(2026-09-18 결정): diverge.write는 memberCount 전원이 idea.submit, diverge.comment는 전원이 아쉬운 점 할당량을 채워야 한다. 아니면 409 NOT_ALL_SUBMITTED(details에 pendingCount·memberCount). 연결이 끊긴 사람 때문에 막히면 진행자가 force=true로 넘길 수 있다(프론트는 확인 창 뒤에만 보냄) — 그때만 제출 안 한 사람이 생긴다.',
          '순서: icebreak → diverge.write → diverge.board → diverge.comment → diverge.review → diverge.vote → diverge.result. lobby는 session.start로, diverge.result는 topic.confirm으로만 넘어간다.',
          '단계를 DB에 먼저 저장하고 나서 이벤트를 보낸다(이벤트를 받은 화면이 session.get으로 확인해도 새 단계가 보이게).',
          '단계에 들어가거나 나갈 때 할 일(제출 마감, AI 작업 시작, 투표 마감 등)은 그 단계를 다루는 차수 전달 문서에 적혀 있다.',
          '9단계에서는 진행자가 team.split → team.questions(겹친 후보가 없으면 바로 team.assign) 로 넘긴다.',
          'team.questions → team.assign 은 겹친 후보가 모두 답하거나 시간이 끝나면 <b>서버가 자동으로</b> 넘긴다(진행자가 먼저 넘길 수도 있음).',
          'team.assign → report 는 이 API가 아니라 <b>팀장의 team.confirm</b> 으로만 넘어간다.'])
ep('session.back', 'POST', '/sessions/{sessionId}/stage/prev', 'host', '이전 단계로 돌아가기',
   '진행자가 직전 단계로 되돌린다(아이스브레이킹 진행자 화면의 "이전 단계").', req={"from": "icebreak"},
   res={"stage": {"id": "icebreak", "label": "아이스브레이킹", "subStep": 5, "progress": 18}})

ep('session.extend', 'PUT', '/sessions/{sessionId}/timer', 'host', '세션 시간 연장',
   '시간이 끝났을 때(또는 끝나기 전) 진행자가 5분 단위로 늘린다. 모두에게 timer.sync 이벤트로 새 endsAt을 보낸다.',
   req={"addMin": 5}, res={"timer": {"endsAt": "2026-09-18T15:37:10+09:00", "remainingSec": 300}},
   errors=[('VALIDATION', 400, 'addMin이 1~30 밖'), ('PLAN_LIMIT', 403, '무료 세션은 총 30분을 넘길 수 없음 (PRO는 제한 없음)'), ('FORBIDDEN', 403, '진행자가 아님'), ('SESSION_STARTED', 409, '아직 시작 전이거나 이미 끝난 세션 → 시작 전 · 종료 후에는 연장 불가')],
   notes=['시간이 끝나도 세션은 자동으로 끝나지 않는다(2026-09-18 결정). 프론트가 00:00이 되면 안내 창을 띄우고, 진행자가 "5분 더"(이 API) 또는 "이대로 계속"(아무 호출 없음)을 고른다.',
          'durationMin이 null(제한 없음)인 세션은 타이머가 없으니 이 API도 쓰지 않는다(400 VALIDATION).',
          '연장 뒤 endsAt은 "지금 + addMin"이 아니라 "원래 endsAt + addMin". 여러 번 눌러도 합계가 한도를 넘으면 403 PLAN_LIMIT.'])

# ───────── 7 아이스브레이킹 ─────────
ICE_TOPICS = ["최근 불편했던 순간", "요즘 이 주제 주변에서 바뀐 것", "그 변화와 내 경험", "요즘 쓰는 서비스와 아쉬운 점", "해보고 싶은 것 · 피하고 싶은 것"]
ep('ice.state', 'GET', '/sessions/{sessionId}/icebreak/me', 'participant', '내 인터뷰 상태',
   '새로고침·재접속 시 내 대화 내용과 몇 번째 질문인지 복구한다. 이 대화는 본인만 볼 수 있다.',
   res={"step": 1, "done": False, "topics": ICE_TOPICS,
        "messages": [{"id": "m1", "role": "ai", "label": None, "style": None, "text": "안녕하세요 노형원님. 저와 1:1로 짧게 이야기해요. …"},
                     {"id": "m2", "role": "ai", "label": "질문 1 · 불편했던 순간", "style": None, "text": "최근 일주일, 가장 불편했던 순간은 언제였어요? 사소한 것도 좋아요."}]},
   notes=['메시지 style: null(기본) · "fq"(꼬리질문, 연보라) · "explain"(뜻풀이, 하늘색) · "good"(인터뷰 끝 안내, 초록 — 마지막 1번만).'])
ep('ice.send', 'POST', '/sessions/{sessionId}/icebreak/messages', 'participant', '인터뷰 답 보내기',
   '내 답을 받아서 AI가 (1) 답이 짧으면 꼬리질문 1번, (2) 충분하면 다음 질문, (3) 마지막이면 끝 안내와 재료를 돌려준다.',
   req={"text": "과제 공지 놓친 거", "clientMessageId": "c_171234"},
   res={"step": 1, "done": False, "messages": [
       {"id": "m4", "role": "ai", "label": "꼬리질문", "style": "fq", "text": "어떤 과제였고, 공지가 **어디에** 올라와 있었어요?"}]},
   errors=[('INTERVIEW_DONE', 409, '이미 끝난 인터뷰')],
   notes=['꼬리질문은 질문당 최대 1번. "짧다/모호하다" 판단은 AI(저가 모델)가 한다.',
          '질문 2로 넘어갈 때 news 카드가 준비 안 됐으면 {"role":"ai","style":"wait"} 안내를 먼저 보내고, 준비되면 icebreak.news.ready 이벤트.',
          '응답이 느리면 SSE/스트리밍으로 바꿔도 된다(프론트는 messages 배열만 그리면 됨).',
          '답 원문은 이 사람 본인에게만 보인다. 진행자·팀원 API 어디에도 원문을 넣지 않는다.'])
ep('ice.skip', 'POST', '/sessions/{sessionId}/icebreak/skip', 'participant', '이 질문 넘어가기',
   '현재 질문(또는 꼬리질문)을 건너뛰고 다음 질문 메시지를 받는다.',
   req={}, res={"step": 2, "done": False, "messages": [{"id": "m9", "role": "ai", "label": "질문 2 · 요즘 바뀐 것", "text": "요즘 '캠퍼스 생활 서비스' 주변 소식이에요. …"}]})
NEWS = [{"cardId": "news_1", "category": "시장", "title": "대학가 중고거래가 앱 밖 단톡방으로 이동", "plain": "거래는 늘었는데 믿을 장치가 없어요", "forTeam": "신뢰·정산을 돕는 도구가 틈새일 수 있어요", "source": {"name": "[기사·매체]", "url": "https://example.com/news/1", "publishedAt": "2026-09-10"}, "myReaction": "heard"},
        {"cardId": "news_2", "category": "기술", "title": "폰 안에서 도는 온디바이스 AI 모델 무료 공개", "plain": "서버 없이도 요약 같은 AI 기능을 넣을 수 있어요", "forTeam": "백엔드가 약해도 AI 시연이 가능해요", "source": {"name": "[공식 블로그]", "url": "https://example.com/news/2", "publishedAt": "2026-09-08"}, "myReaction": "new"},
        {"cardId": "news_3", "category": "규제", "title": "학생 개인정보 동의 절차 강화", "plain": "학번·시간표를 쓰면 동의 화면이 더 분명해야 해요", "forTeam": "학생 정보를 쓰면 동의 흐름도 기능이에요", "source": {"name": "[기관 보도자료]", "url": "https://example.com/news/3", "publishedAt": "2026-09-05"}, "myReaction": None}]
ep('ice.news', 'GET', '/sessions/{sessionId}/icebreak/news', 'participant', '최근 소식 카드 3장',
   '세션 주제로 실제 검색한 결과에서 시장·기술·규제 카드 3장을 만든다. 모든 참가자가 같은 카드를 본다.',
   res={"ready": True, "cards": NEWS},
   notes=['검색 API(예: Brave)로 최근 기사·공식 자료를 찾고, 검색 결과에 있는 내용만 AI가 쉬운 말로 요약한다(지어내기 금지).',
          '검색 실패 시 {"ready": true, "cards": [], "fallback": true} → 프론트는 질문 2·3을 건너뛴다.',
          '세션 시작 때 미리 만들어 캐시해 두면 질문 2에서 기다리는 시간이 없다.'])
ep('ice.react', 'PUT', '/sessions/{sessionId}/icebreak/news/{cardId}/reaction', 'participant', '소식 카드 반응',
   '처음 들어요 · 들어봤어요 · 잘 알아요 중 하나. 다시 누르면 바뀐다.',
   req={"reaction": "new | heard | know"}, res={"cardId": "news_2", "myReaction": "new"},
   notes=['진행자 화면에는 사람 이름 없이 인원 수만 집계해서 보여준다.'])
ep('ice.explain', 'POST', '/sessions/{sessionId}/icebreak/explain', 'participant', '"이게 뭐예요?" 뜻풀이',
   '카드 속 어려운 말을 쉬운 말로 풀어 대화창에 넣어준다. 물어본 말은 "내가 물어본 말"에 쌓인다.',
   req={"cardId": "news_2", "term": "온디바이스 AI"},
   res={"message": {"id": "m7", "role": "ai", "style": "explain", "text": "**온디바이스 AI**는 인터넷 서버를 거치지 않고 폰이나 노트북 안에서 바로 도는 AI예요. …"},
        "askedTerms": ["온디바이스 AI"]})
ep('ice.progress', 'GET', '/sessions/{sessionId}/icebreak/progress', 'participant', '팀 인터뷰 진행',
   '오른쪽 "팀 진행" 카드. 답 내용은 없이 몇 번째 질문인지만.',
   res={"items": [{"nickname": "노형원", "isMe": True, "step": 1, "done": False}, {"nickname": "이세민", "step": 2, "done": False},
                  {"nickname": "김승희", "step": 2, "done": False}, {"nickname": "박상진", "step": 0, "done": False}]},
   notes=['변경될 때마다 icebreak.progress 실시간 이벤트로도 보낸다.'])
ep('ice.myMaterials', 'GET', '/sessions/{sessionId}/icebreak/materials/me', 'participant', '내 답에서 뽑힌 재료 (나만 보임)',
   '인터뷰가 끝나면 AI가 내 답에서 뽑은 재료 목록. "피할 것"만 따로 표시한다.',
   res={"items": [{"text": "교양 과제 공지가 메일로만 와서 마감을 놓침", "avoid": False},
                  {"text": "단톡방 공동구매가 늘며 정산을 한 사람이 떠안음", "avoid": False},
                  {"text": "피그마 수정 내역 추적이 어렵고, 노션엔 팀원이 잘 안 들어옴", "avoid": False},
                  {"text": "AI 기능을 직접 넣어보고 싶음", "avoid": False},
                  {"text": "학교 앞 카페 콘센트 자리 경쟁", "avoid": False},
                  {"text": "앱 개발", "avoid": True}]},
   notes=['재료는 이름 없이 발산 단계로 넘어간다. 삭제·빼기 기능은 없다(디자인 결정).'])
GROUPS = [{"groupId": "grp_1", "title": "흩어진 학교 정보", "desc": '묶으면 "캠퍼스 정보를 한곳에서" 방향이 돼요', "aiPick": True, "focus": True,
           "items": [{"text": "과제 공지가 메일·LMS·단톡으로 흩어짐", "count": 2, "avoid": False}, {"text": "시험기간 열람실 빈자리 찾기", "count": 1, "avoid": False}, {"text": "학교 앞 카페 콘센트 자리 경쟁", "count": 1, "avoid": False}]},
          {"groupId": "grp_2", "title": "AI를 직접 써보고 싶음", "desc": "동기가 가장 많이 겹치고, 최근 소식과도 이어져요", "aiPick": False, "focus": True,
           "items": [{"text": "AI 기능을 직접 넣어보고 싶음", "count": 3, "avoid": False}, {"text": "온디바이스 AI로 서버 없이 시연", "count": 1, "avoid": False}]},
          {"groupId": "grp_3", "title": "돈·정산의 신뢰", "desc": "최근 시장 변화와 실제 경험이 맞닿아 있어요", "aiPick": False, "focus": False,
           "items": [{"text": "단톡방 공동구매 정산을 한 사람이 떠안음", "count": 1, "avoid": False}]},
          {"groupId": "grp_4", "title": "우리 팀의 조건", "desc": "주제가 아니라 범위를 정하는 재료예요", "aiPick": False, "focus": None,
           "items": [{"text": "웹 화면과 발표 자료는 자신 있음", "count": 2, "avoid": False}, {"text": "앱 개발 · 서버가 무거운 방향", "count": 2, "avoid": True}]}]
ep('ice.overview', 'GET', '/sessions/{sessionId}/icebreak/overview', 'host', '진행자 요약 (진도 · 소식 반응 · 재료 묶음)',
   '진행자 화면(7-6). 사람별 진도, 소식 카드 반응 인원 수, AI가 묶은 재료 그룹.',
   res={"progress": [{"nickname": "노형원", "step": 5, "done": True}, {"nickname": "이세민", "step": 5, "done": True},
                     {"nickname": "김승희", "step": 5, "done": True}, {"nickname": "박상진", "step": 4, "done": False}],
        "newsReactions": [{"cardId": "news_1", "category": "시장", "title": "단톡방 중고거래", "counts": {"new": 1, "heard": 2, "know": 1}},
                          {"cardId": "news_2", "category": "기술", "title": "온디바이스 AI", "counts": {"new": 3, "heard": 0, "know": 1}},
                          {"cardId": "news_3", "category": "규제", "title": "학생 정보 동의 강화", "counts": {"new": 4, "heard": 0, "know": 0}}],
        "hint": "온디바이스 AI를 잘 아는 사람이 1명 있어요. 발산 때 설명을 부탁해 보세요.",
        "materialCount": 11, "groups": GROUPS},
   notes=['focus: true(먼저 보기로 표시) · false(표시 안 함) · null(표시 대상 아님 — "우리 팀의 조건"처럼 범위용 그룹).',
          '"잘 아는 사람이 1명" 같은 힌트도 이름 없이 인원 수로만.',
          '늦게 끝난 사람 답이 들어오면 icebreak.groups.updated 이벤트로 알리고, 진행자가 "다시 묶기"를 눌러야 반영.'])
ep('ice.regroup', 'POST', '/sessions/{sessionId}/icebreak/groups/regroup', 'host', '재료 다시 묶기',
   '지금까지 모인 재료로 AI 묶음을 다시 만든다. 먼저 보기 표시는 비슷한 그룹에 최대한 이어 붙인다.', req={}, res={"groups": GROUPS})
ep('ice.focus', 'PUT', '/sessions/{sessionId}/icebreak/groups/{groupId}/focus', 'host', '"먼저 보기" 표시',
   '진행자는 재료를 고르지 않고, 먼저 이야기할 묶음만 표시한다.', req={"focus": True}, res={"groupId": "grp_3", "focus": True})
ep('ice.materials', 'GET', '/sessions/{sessionId}/materials', 'participant', '발산 재료 (모두)',
   '발산 화면 위쪽에 보여줄 재료. 먼저 보기 묶음은 펼치고 나머지는 한 줄. 이름·출처 없음.',
   res={"total": 11, "focusGroups": [g for g in GROUPS if g["focus"]], "otherGroups": [g for g in GROUPS if not g["focus"]]})

# ───────── 8 발산 ─────────
ep('idea.mine', 'GET', '/sessions/{sessionId}/ideas/me', 'participant', '내 아이디어 1·2·3순위 불러오기', '작성 중이던 내용을 복구한다.',
   res={"submitted": False, "ideas": [{"rank": 1, "text": "과제 공지와 마감을 메일·학교 사이트·단톡에서 한곳에 모아 알려주는 웹", "source": "own"},
                                      {"rank": 2, "text": "강의자료 PDF를 요약해 주는 브라우저 도구", "source": "own"}]})
ep('idea.submit', 'PUT', '/sessions/{sessionId}/ideas/me', 'participant', '내 아이디어 제출',
   '최대 3개를 순위와 함께 제출한다. AI 추천에서 고른 것도 source만 다르고 팀에는 똑같이 "내 아이디어"로 보인다.',
   req={"ideas": [{"rank": 1, "text": "과제 공지와 마감을 한곳에 모아 알려주는 웹", "source": "own"},
                  {"rank": 2, "text": "학교 행사·특강 소식 중 관심 있는 것만 골라 알려주는 웹", "source": "ai", "recommendationId": "rec_1"}]},
   res={"submitted": True, "submittedCount": 3, "memberCount": 4},
   errors=[('VALIDATION', 400, '0개 또는 4개 이상 · 빈 문장 · 순위 중복'), ('STAGE_CLOSED', 409, '이미 다음 단계')],
   notes=['source("own"|"ai")는 서버 내부 통계용. 다른 사람에게 보내는 어떤 응답에도 넣지 않는다.',
          '아이디어 주인(participantId)은 저장하되, 투표 결과(8-7) 전까지는 어떤 응답에도 넣지 않는다.',
          '제출할 때마다 ideas.submitted 이벤트(인원 수만)를 보낸다.'])
ep('idea.recommend', 'GET', '/sessions/{sessionId}/ideas/recommendations', 'participant', 'AI 추천 아이디어',
   '내 인터뷰 재료와 프로필을 바탕으로 추천 4개. "다른 추천 더 보기"는 cursor로.',
   query={"cursor": "다음 묶음 커서"},
   res={"items": [{"recommendationId": "rec_1", "title": "학교 행사·특강 소식 중 관심 있는 것만 골라 알려주는 웹", "reason": '"중요한 공지를 자주 놓친다"고 했어요'},
                  {"recommendationId": "rec_2", "title": "중고 전공책을 같은 학과 안에서만 사고파는 게시판", "reason": '"학기마다 책값이 부담"이라고 했어요'},
                  {"recommendationId": "rec_3", "title": "팀플 회비를 누가 냈는지 링크 하나로 확인하는 웹", "reason": '최근 소식 "단톡방 거래 증가"를 들어봤어요'},
                  {"recommendationId": "rec_4", "title": "디자인 수정 요청을 한 화면에 모아 보는 팀플 도구", "reason": '"피그마에서 누가 어디를 고쳤는지 모르겠다"고 했어요'}],
        "nextCursor": "rec_page_2"},
   errors=[('STAGE_CLOSED', 409, '아이디어 쓰기 단계(diverge.write)가 아님'), ('VALIDATION', 400, '알 수 없는 cursor'),
           ('TOO_MANY_ATTEMPTS', 429, '"더 보기" 너무 많이 (사람당 5묶음까지)'), ('AI_UNAVAILABLE', 503, 'AI 호출 실패 → "추천을 불러오지 못했어요"')],
   notes=['추천 이유는 "내 답"만 인용한다. 다른 사람 답을 인용하면 안 된다.',
          'AI에 넣는 것: 요청한 사람의 인터뷰 재료 · 그 사람 프로필 스냅샷(역할 · 스킬) · 세션 주제 · 심사기준. 이름 · 이메일 · 다른 사람 재료는 넣지 않는다.',
          '추천 이유에 따옴표로 인용한 말은 서버가 그 사람의 답 · 재료에 실제로 있는지 확인하고, 없으면 그 추천은 버린다(다른 사람 답이 새는 것 방지).',
          '만든 묶음은 저장해 두고 같은 cursor로 다시 부르면 AI를 다시 부르지 않고 같은 결과를 준다. 이미 보여준 추천은 다음 묶음에 다시 나오지 않게.',
          '더 만들 게 없으면 nextCursor = null.'])
ep('idea.board', 'GET', '/sessions/{sessionId}/ideas/board', 'participant', '익명 순위표',
   '모두의 1·2·3순위를 이름 대신 팀원 A·B·C·D로. 줄 순서는 세션마다 무작위로 한 번 섞어서 고정.',
   res={"submittedCount": 4, "memberCount": 4,
        "rows": [{"alias": "A", "isMe": False, "ideas": [{"ideaId": "ide_a1", "rank": 1, "text": "열람실·카페 빈자리를 함께 알려주는 지도"}, {"ideaId": "ide_a2", "rank": 2, "text": "팀플 회의가 끝나면 할 일을 정리해 주는 서비스"}, {"ideaId": "ide_a3", "rank": 3, "text": "내 필기로 시험 예상 문제를 만들어 주는 웹"}]},
                 {"alias": "C", "isMe": True, "ideas": [{"ideaId": "ide_c1", "rank": 1, "text": "과제 공지와 마감을 한곳에 모아 알려주는 웹"}]}]},
   notes=['alias(A~D)와 실제 사람 연결은 서버만 안다. 진행자에게도 주지 않는다.', 'isMe는 요청한 본인 줄에만 true.'])
ep('comment.targets', 'GET', '/sessions/{sessionId}/comments/targets', 'participant', '댓글 달 목록 + 내 할당량',
   '왼쪽 목록(내 아이디어 제외)과 오른쪽 위 "아쉬운 점 4/9 · 좋은 점 1/2".',
   res={"quota": {"concernDone": 4, "concernTotal": 9, "praiseUsed": 1, "praiseMax": 2},
        "groups": [{"alias": "A", "items": [{"ideaId": "ide_a1", "rank": 1, "title": "열람실·카페 빈자리 지도", "status": "done", "praised": True}]},
                   {"alias": "B", "items": [{"ideaId": "ide_b1", "rank": 1, "title": "관심 있는 학교 소식만 골라 알려주는 웹", "status": "todo"}]}]})
ep('comment.list', 'GET', '/sessions/{sessionId}/ideas/{ideaId}/comments', 'participant', '먼저 남겨진 익명 댓글',
   '선택한 아이디어의 댓글. 작성자 정보는 절대 포함하지 않는다.',
   res={"idea": {"ideaId": "ide_b1", "alias": "B", "rank": 1, "text": "학교 행사·특강 소식 중 관심 있는 것만 골라 알려주는 웹"},
        "counts": {"concern": 2, "praise": 1},
        "items": [{"type": "concern", "text": "관심사를 처음에 고르는 게 귀찮을 수 있어요. 고르지 않아도 일단 보이게 하면 좋겠어요"},
                  {"type": "concern", "text": "에브리타임 공지 게시판과 겹칠 수 있어요"},
                  {"type": "praise", "text": "공지를 따로 찾아다닐 필요가 없어져요"}],
        "mine": None},
   notes=['mine: 내가 이미 쓴 댓글이 있으면 수정할 수 있게 내 것만 따로 준다.', '댓글 순서는 작성 순서가 아니라 무작위/유형순으로(작성 시각으로 사람을 추측하지 못하게).'])
ep('comment.create', 'POST', '/sessions/{sessionId}/ideas/{ideaId}/comments', 'participant', '익명 댓글 저장',
   '아쉬운 점(필수) + 좋은 점(선택). 한 아이디어에 내 댓글은 1개만(다시 저장하면 수정).',
   req={"concern": "학교마다 공지 사이트가 달라서 자동으로 모으기 어려울 것 같아요. 처음엔 우리 학교 한 곳만 해야 할 듯해요", "praise": None},
   res={"saved": True, "quota": {"concernDone": 5, "concernTotal": 9, "praiseUsed": 1, "praiseMax": 2}}, status=201,
   errors=[('VALIDATION', 400, '아쉬운 점 비어 있음'), ('OWN_IDEA', 403, '내 아이디어에는 댓글 불가'), ('PRAISE_LIMIT', 409, '좋은 점 2개 초과')],
   notes=['좋은 점 2개 제한은 세션 전체 기준(1인당).', 'comments.progress 이벤트로 진행자에게 "몇 명이 다 썼는지"만 알린다.'])
REVIEW = {"ideaId": "ide_c1", "alias": "C", "rank": 1, "title": "과제 공지와 마감을 한곳에 모아 알려주는 웹", "status": "done", "grade": "go",
          "exists": {"label": "비슷한 게 있음", "summary": "일정 관리 앱은 많지만, 여러 곳의 학교 공지를 모아주는 건 드물어요.", "searchUrl": "https://search.example.com/?q=..."},
          "feasibility": {"level": "상", "summary": "웹 화면 2명 · 백엔드 1명이 있어요. 학교 사이트 자동 연결 대신 링크를 붙여넣는 방식이면 지금 수준으로 충분해요."},
          "missingSkills": {"count": 1, "summary": "메일·LMS 자동 연동(API) 경험 — 없어도 시연은 돼요."},
          "need": {"label": "있음", "summary": "인터뷰에서 2명이 공지를 놓쳐 마감을 넘긴 경험을 말했어요."},
          "timeline": {"label": "가능", "summary": "모으기·마감 알림만 하면 해커톤 기간 안에 시연할 수 있어요."},
          "commentSummary": {"concern": 3, "praise": 2, "concernPoints": ["학교마다 공지 사이트가 달라요", "알림이 많으면 귀찮아요"], "praisePoints": ["다들 겪는 문제라 공감이 커요", "발표하기 쉬워요"]}}
ep('review.list', 'GET', '/sessions/{sessionId}/reviews', 'participant', 'AI 검증 등급별 목록',
   '12개 아이디어를 3등급으로 묶은 왼쪽 목록. 등급과 상관없이 모두 투표에 올라간다.',
   res={"ready": True, "total": 12, "doneCount": 12, "groups": [{"grade": "go", "label": "바로 해볼 만해요", "items": [{"ideaId": "ide_c1", "title": "과제 공지와 마감을 한곳에 모아 알려주는 웹"}]},
                                               {"grade": "fix", "label": "보완하면 좋아요", "items": [{"ideaId": "ide_a1", "title": "열람실·카페 빈자리 지도"}]},
                                               {"grade": "re", "label": "다시 생각해 봐요", "items": [{"ideaId": "ide_c2", "title": "강의자료 PDF 요약 도구"}]}]},
   notes=['검증이 다 끝나기 전엔 ready=false. 끝나면 reviews.ready 이벤트.',
          '검증은 diverge.review 단계에 들어갈 때 시작한다. ready=false인 동안(단계 전 포함)은 {"ready": false, "total": 아이디어 수, "groups": []} — 일부 결과만 먼저 주지 않는다.',
          '"다 끝남" = 모든 아이디어가 done 또는 failed. 실패한 아이디어는 {"grade": "failed", "label": "검증하지 못했어요", "items": [...]} 그룹에 넣는다(그룹은 있는 것만).',
          '그룹 안 순서는 작성자 · 작성 시각과 상관없이 세션마다 한 번 섞어서 고정. AI가 모은 아이디어는 이 목록에 넣지 않는다(투표 목록에서 따로).'])
ep('review.get', 'GET', '/sessions/{sessionId}/ideas/{ideaId}/review', 'participant', 'AI 검증 상세', '오른쪽 본문(이미 있나·구현 가능성·없는 스킬·필요·기간·댓글 요약).', res=REVIEW,
   notes=['grade: go(바로 해볼 만해요) · fix(보완하면 좋아요) · re(다시 생각해 봐요).',
          'exists는 실제 검색 결과가 근거여야 하고 searchUrl을 꼭 준다. 나머지는 AI 판단(참고용).',
          '구현 가능성은 팀원 스킬을 "인원 수"로만 AI에 보낸다(예: 웹 화면 2명). 이름은 AI에 보내지 않는다.',
          'status: pending(아직) · done · failed. pending · failed면 grade와 6개 관점이 모두 null.',
          'commentSummary의 concern · praise 개수는 실제 댓글 개수와 같아야 한다. 요점(points)은 작성자 없이 AI 요약.',
          'exists의 검색 결과에 링크가 없으면 exists는 {"label": "확인 못 함", "summary": "검색 결과가 없어요", "searchUrl": null} — 지어내지 않기.'],
   errors=[('NOT_FOUND', 404, '이 세션에 없는 아이디어')])
ep('vote.state', 'GET', '/sessions/{sessionId}/vote', 'participant', '투표 화면 목록 + 내 표',
   '왼쪽 레일: 투표 후보(12) · AI가 모은 아이디어(2) · 숨은 공통점(3, 선택지 아님). 1인 2표.',
   res={"maxVotes": 2, "myVotes": ["ide_c1"], "votedCount": 3, "memberCount": 4, "finished": False,
        "candidates": [{"id": "ide_c1", "kind": "idea", "title": "과제 공지와 마감을 한곳에 모아 알려주는 웹", "grade": "go", "isMine": True},
                       {"id": "ide_b1", "kind": "idea", "title": "관심 있는 학교 행사·특강 소식만 골라 알려주는 웹", "grade": "go", "isMine": False},
                       {"id": "ide_a2", "kind": "idea", "title": "팀플 회의가 끝나면 할 일을 정리해 주는 서비스", "grade": "go", "isMine": False}],
        "aiIdeas": [{"id": "aii_1", "kind": "ai", "title": "시험기간에만 여는 열람실·카페 빈자리·콘센트 제보판", "grade": "go"},
                    {"id": "aii_2", "kind": "ai", "title": "팀플 자료·수정 요청을 링크 하나에 모으고 바뀐 점만 요약", "grade": "fix"}],
        "commonThreads": [{"id": "thr_1", "title": '"누가 무엇을 했는지"가 한곳에 안 남아요', "candidateCount": 4},
                          {"id": "thr_2", "title": "알림이 너무 많아 중요한 걸 놓쳐요", "candidateCount": 2},
                          {"id": "thr_3", "title": "AI는 넣고 싶지만 무거운 서버는 피하고 싶어요", "candidateCount": 2}]},
   notes=['isMine은 요청한 본인 아이디어에만 true (다른 사람 아이디어의 주인은 아직 비공개).'])
ep('vote.candidate', 'GET', '/sessions/{sessionId}/vote/candidates/{ideaId}', 'participant', '투표 후보 상세',
   '누르면 오른쪽에 처음 적은 내용 · AI 검증 요약 · 익명 댓글을 다시 보여준다.',
   res={"ideaId": "ide_a2", "alias": "A", "rank": 2, "title": "팀플 회의가 끝나면 할 일을 정리해 주는 서비스", "grade": "go",
        "originalText": "회의 메모나 녹음을 올리면 누가 언제까지 뭘 해야 하는지 정리해서 단톡방에 보내주는 서비스",
        "review": {"exists": {"label": "비슷한 게 있음", "summary": "회의록 AI는 많지만 대학 팀플·단톡 공유에 맞춘 건 드물어요.", "searchUrl": "https://search.example.com/?q=..."},
                   "feasibility": {"level": "상", "summary": "텍스트 메모부터 시작하면 돼요."},
                   "need": {"label": "있음", "summary": "인터뷰에서 3명이 비슷한 경험을 말했어요."},
                   "timeline": {"label": "가능", "summary": "메모 입력과 할 일 정리 화면만 하면 시연할 수 있어요."}},
        "comments": {"concern": 3, "praise": 2, "items": [{"type": "concern", "text": "회의 메모를 누가 정리해서 올릴지가 또 문제예요"}, {"type": "praise", "text": "팀플마다 겪는 문제라 발표할 때 공감을 얻기 쉬워요"}]},
        "votedByMe": False})
ep('vote.aiIdea', 'GET', '/sessions/{sessionId}/ai-ideas/{aiIdeaId}', 'participant', 'AI가 모은 아이디어 상세',
   '어떤 아이디어에서 좋은 점을 가져왔는지, 아쉬운 점을 어떻게 줄였는지, 새로 한 AI 검증.',
   res={"id": "aii_1", "title": "시험기간에만 여는 열람실·카페 빈자리·콘센트 제보판", "grade": "go",
        "sources": [{"alias": "A", "rank": 1, "title": "열람실·카페 빈자리를 함께 알려주는 지도", "grade": "fix", "takenPoint": "시험기간엔 누구나 겪는 문제라 공감이 커요"},
                    {"alias": "D", "rank": 3, "title": "학교 앞 카페 콘센트 자리 알림", "grade": "re", "takenPoint": "콘센트 자리는 실제로 다들 찾아다녀요"}],
        "fixes": [{"problem": "실시간 정보가 틀릴 수 있어요", "concernCount": 3, "fix": '제보 시간과 "지금도 맞아요" 확인 수를 같이 보여주기'},
                  {"problem": "평소엔 쓸 일이 별로 없어요", "concernCount": 2, "fix": "시험기간 2주만 여는 서비스로 범위 줄이기"}],
        "review": {"exists": "비슷한 게 있음", "feasibility": "상", "need": "있음", "timeline": "가능", "searchUrl": "https://search.example.com/?q=..."}},
   notes=['AI 아이디어는 "AI가 모음" 표시를 항상 붙이고, 원래 아이디어보다 낫다고 내세우는 문구를 쓰지 않는다.',
          '좋은 점을 받은(praise가 있는) 아이디어들에서만 만든다. 최대 2개. 좋은 점을 받은 아이디어가 없으면 만들지 않는다(vote.state의 aiIdeas = []).',
          'AI 검증 작업과 같이(diverge.review에 들어갈 때) 만들고, 만든 아이디어에도 같은 검증을 돌린다. 모두 끝나야 reviews.ready.',
          'sources에는 별칭(alias) · 순위 · 제목만. 주인 이름은 투표 결과(vote.results의 sourceOwners)에서만 공개.'],
   errors=[('FORBIDDEN', 403, '투표 단계(diverge.vote) 전'), ('NOT_FOUND', 404, '이 세션에 없는 id')])
ep('vote.thread', 'GET', '/sessions/{sessionId}/common-threads/{threadId}', 'participant', '숨은 공통점 상세 (투표 참고)',
   '서로 다른 묶음에 흩어져 있던 재료가 사실 같은 문제라는 AI의 연결. 투표 선택지가 아니다.',
   res={"id": "thr_1", "title": '팀플에서 "누가 무엇을 했는지"가 한곳에 남지 않아요', "answerCount": 3, "includesMine": True,
        "sources": [{"question": "질문 1 · 불편", "summary": "과제 공지가 메일·LMS·단톡으로 흩어져 마감을 놓침"},
                    {"question": "질문 1 · 불편", "summary": "팀플 회비를 누가 냈는지 헷갈림"},
                    {"question": "질문 4 · 쓰는 서비스", "summary": "피그마 수정 내역을 추적하기 어렵고, 노션엔 팀원이 잘 안 들어옴"}],
        "why": '세 재료는 서로 다른 묶음(흩어진 학교 정보 · 돈·정산 · 팀의 조건)에 있었어요. 겉은 달라도 모두 "기록이 한곳에 없다"는 같은 문제예요.',
        "candidates": [{"id": "ide_c1", "title": "과제 공지와 마감을 한곳에 모아 알려주는 웹", "grade": "go", "isMine": True, "votedByMe": True},
                       {"id": "aii_2", "title": "팀플 자료·수정 요청을 링크 하나에 모으고 바뀐 점만 요약", "grade": "fix", "isAi": True, "votedByMe": False}],
        "myReaction": "didntKnow"},
   notes=['2명 이상의 답이 겹칠 때만 만든다.', 'sources는 요약만, 답 원문 인용 금지. 누가 말했는지는 진행자도 모른다.',
          'includesMine은 본인에게만 계산해서 준다.',
          '투표 단계(diverge.vote) 전에는 id가 맞든 틀리든 403 FORBIDDEN (선입견 방지 — 아이디어 제출이 끝난 뒤, 투표 때만 공개).',
          '만드는 때: diverge.board에 들어갈 때(아이디어 제출 마감 후). 재료 묶음 + 아이디어를 넣고, 서로 다른 묶음에 있던 재료만 잇는다. 최대 3개.',
          'candidates의 isMine · votedByMe는 요청한 사람 기준.'],
   errors=[('FORBIDDEN', 403, '투표 단계(diverge.vote) 전'), ('NOT_FOUND', 404, '이 세션에 없는 id')])
ep('vote.threadReact', 'PUT', '/sessions/{sessionId}/common-threads/{threadId}/reaction', 'participant', '"이 연결, 알고 있었나요?"',
   '몰랐어요 · 이미 알았어요. 기능 개선용 통계.', req={"reaction": "didntKnow | knew"}, res={"myReaction": "didntKnow"},
   errors=[('VALIDATION', 400, 'reaction 값이 didntKnow · knew가 아님'), ('FORBIDDEN', 403, '투표 단계(diverge.vote) 전'), ('NOT_FOUND', 404, '이 세션에 없는 id')],
   notes=['다시 보내면 마지막 값으로 바뀐다(PUT).', '통계는 서비스 개선용. 진행자 · 팀원 화면 어디에도 보여주지 않는다.'])
ep('vote.save', 'PUT', '/sessions/{sessionId}/vote/me', 'participant', '내 표 저장 (최대 2표)',
   '체크한 후보 전체를 보낸다(추가·취소를 한 번에). 아이디어와 AI 아이디어 모두 1표씩.',
   req={"ids": ["ide_c1", "ide_a2"]}, res={"myVotes": ["ide_c1", "ide_a2"], "remaining": 0},
   errors=[('VOTE_LIMIT', 409, '2표 초과'), ('NOT_A_CANDIDATE', 400, '숨은 공통점 등 후보가 아닌 id'), ('VOTE_FINISHED', 409, '투표 마치기 이후')],
   notes=['누가 어디에 투표했는지는 끝까지 비공개. 결과 집계에서만 합계로 쓴다.', '자기 아이디어에 투표하는 것은 허용(디자인상 체크됨).'])
ep('vote.finish', 'POST', '/sessions/{sessionId}/vote/me/finish', 'participant', '투표 마치기',
   '내 투표를 확정한다. 모두 마치면 결과가 열린다(vote.closed 이벤트).', req={},
   res={"finished": True, "votedCount": 4, "memberCount": 4})
ep('vote.results', 'GET', '/sessions/{sessionId}/vote/results', 'participant', '투표 결과 + 아이디어 주인 공개',
   '표 수 순위와 함께 이때 처음으로 아이디어 주인 이름을 공개한다. 댓글 작성자·투표자는 계속 비공개.',
   res={"totalVotes": 8, "memberCount": 4, "unvotedCount": 9,
        "ranks": [{"rank": 1, "id": "ide_c1", "title": "과제 공지와 마감을 한곳에 모아 알려주는 웹", "grade": "go", "votes": 3, "owner": {"nickname": "노형원", "rank": 1}},
                  {"rank": 2, "id": "ide_b1", "title": "관심 있는 학교 행사·특강 소식만 골라 알려주는 웹", "grade": "go", "votes": 2, "owner": {"nickname": "김승희", "rank": 1}},
                  {"rank": 3, "id": "ide_a2", "title": "팀플 회의가 끝나면 할 일을 정리해 주는 서비스", "grade": "go", "votes": 1, "owner": {"nickname": "이세민", "rank": 2}},
                  {"rank": 3, "id": "aii_1", "title": "시험기간에만 여는 열람실·카페 빈자리·콘센트 제보판", "grade": "go", "votes": 1, "aiMerged": True, "sourceOwners": [{"nickname": "이세민", "rank": 1}, {"nickname": "박상진", "rank": 3}]},
                  {"rank": 3, "id": "ide_b2", "title": "중고 전공책을 같은 학과 안에서만 사고파는 게시판", "grade": "go", "votes": 1, "owner": {"nickname": "김승희", "rank": 2}}],
        "ties": [{"rank": 3, "ids": ["ide_a2", "aii_1", "ide_b2"]}],
        "insight": {"title": '1위와 "회의 후 할 일 정리"는 같은 숨은 공통점에서 나왔어요', "body": '둘 다 팀플에서 "누가 무엇을 했는지"가 한곳에 남지 않는 문제를 풀어요. …', "threadId": "thr_1"}},
   errors=[('VOTE_NOT_CLOSED', 409, '아직 투표 중')],
   notes=['표를 받지 못한 아이디어도 주인과 함께 기록에 남긴다(unvotedCount).'])
ep('vote.revote', 'POST', '/sessions/{sessionId}/vote/revote', 'host', '동점만 다시 투표',
   '동점 후보만 가지고 짧은 재투표를 연다. 모두의 화면이 투표(8-6)로 돌아가고 후보가 줄어든다.',
   req={"ids": ["ide_a2", "aii_1", "ide_b2"], "maxVotes": 1}, res={"revoteId": "rv_1", "candidates": ["ide_a2", "aii_1", "ide_b2"]})
ep('topic.confirm', 'POST', '/sessions/{sessionId}/topic', 'host', '주제 확정 (+ 팀장 정하기)',
   '선택한 아이디어를 세션 주제로 확정하고 파트 나누기 단계(9-1)로 넘긴다. 기본값은 1위.',
   req={"ideaId": "ide_c1", "leaderParticipantId": "par_03"},
   res={"topic": {"ideaId": "ide_c1", "title": "과제 공지와 마감을 한곳에 모아 알려주는 웹"},
        "leader": {"participantId": "par_03", "nickname": "김승희"},
        "stage": {"id": "team.split", "label": "파트 나누기 · 보고서", "subStep": 2, "progress": 70}},
   notes=['확정되면 topic.confirmed + stage.changed 이벤트. <b>파트 나누기 AI 작업(11)</b>을 이때 시작한다 → 끝나면 team.parts.ready.',
          'leaderParticipantId(팀장)는 <b>선택</b>이다. 안 보내면 진행자가 팀장이 된다. 8-7에 팀장 고르기 UI는 아직 디자인이 없다(디자인 확인 필요).',
          '팀장은 배치 초안을 고치고 확정하는 사람이다(9-4). 진행자와 달라도 된다.'])

# ───────── 9 파트 나누기 · 배치 · 보고서 ─────────
# 사람: par_01 노형원(진행자) · par_02 이세민 · par_03 김승희(팀장) · par_04 박상진
P = {"노형원": "par_01", "이세민": "par_02", "김승희": "par_03", "박상진": "par_04"}
def who(n, me=False):
    d = {"participantId": P[n], "nickname": n}
    if me: d["isMe"] = True
    return d
TEAM_STAGE = {"id": "team.split", "label": "파트 나누기 · 보고서", "subStep": 2, "progress": 70}
PARTS = [
    {"partId": "prt_1", "tier": "core", "name": "화면 만들기", "desc": "공지 목록 · 마감 알림 화면", "skill": "프론트엔드", "status": "overlap", "candidates": [who("노형원", True), who("이세민")]},
    {"partId": "prt_2", "tier": "core", "name": "서버 · 공지 모으기", "desc": "게시판 글 가져오기 · 알림 보내기", "skill": "백엔드", "status": "single", "candidates": [who("박상진")]},
    {"partId": "prt_3", "tier": "core", "name": "발표 · 시연", "desc": "문제 정의 · 시연 흐름 · 질의응답", "skill": "발표·피칭", "status": "overlap", "candidates": [who("노형원", True), who("이세민")]},
    {"partId": "prt_4", "tier": "normal", "name": "화면 디자인", "desc": "화면 분위기 · 컴포넌트 스타일", "skill": "웹 디자인", "status": "overlap", "candidates": [who("이세민"), who("김승희")]},
    {"partId": "prt_5", "tier": "normal", "name": "발표 자료", "desc": "장표 구성 · 시각화", "skill": "PPT 디자인", "status": "single", "candidates": [who("김승희")]},
    {"partId": "prt_6", "tier": "normal", "name": "기획 · 범위 관리", "desc": "기능 범위 · 진행 조율", "skill": "서비스 기획", "status": "single", "candidates": [who("노형원", True)]},
    {"partId": "prt_7", "tier": "normal", "name": "메일·LMS 자동 연동", "desc": "AI 검증에서 나온 팀에 없는 스킬", "skill": "외부 API 연동", "status": "none", "candidates": [], "alternative": "링크 붙여넣기로 대신하기"},
]
SMALL = [("prt_s1", "경쟁 서비스 조사", "이세민"), ("prt_s2", "사용자 인터뷰 3명", "김승희"), ("prt_s3", "시연용 예시 공지 만들기", "이세민"),
         ("prt_s4", "제출 문서 · 보고서 정리", "김승희"), ("prt_s5", "기능 테스트 · 버그 기록", "이세민"), ("prt_s6", "회의록 · 일정 챙기기", "박상진")]
ep('team.parts', 'GET', '/sessions/{sessionId}/team/parts', 'participant', '파트와 후보 (9-1)',
   '확정된 주제를 파트로 나누고, 파트마다 프로필 스킬로 찾은 후보를 준다. 후보가 2명 이상이면 overlap(추가 질문), 1명이면 single(바로 배정), 없으면 none(대안 제안).',
   res={"ready": True,
        "topic": {"ideaId": "ide_c1", "title": "과제 공지와 마감을 한곳에 모아 알려주는 웹", "owner": {"nickname": "노형원", "rank": 1}, "votes": 3, "feasibility": "상"},
        "parts": PARTS,
        "smallTasks": {"count": 6, "names": [n for _, n, _ in SMALL], "note": "분량이 비슷해지게 나눠요"},
        "mine": [{"partId": "prt_1", "name": "화면 만들기", "status": "overlap"}, {"partId": "prt_3", "name": "발표 · 시연", "status": "overlap"},
                 {"partId": "prt_6", "name": "기획 · 범위 관리", "status": "single"}],
        "myPendingQuestions": 0},
   errors=[('NOT_PARTICIPANT', 403, '이 세션 참가자가 아님')],
   notes=['주제 확정(topic.confirm) 직후 AI 작업 11(파트 나누기)이 돈다. 끝나기 전에는 {"ready": false} → 끝나면 team.parts.ready 이벤트.',
          'tier: core(결과를 좌우하는 파트) · normal(보통 파트) · small(작은 일, 스킬 없이 누구나). small은 parts에 넣지 않고 smallTasks로 이름만 준다(9-3에서 사람에게 나눔).',
          '후보는 참가자 프로필 스냅샷의 "할 수 있는 것"(skills)과 파트의 필요한 스킬로 정한다. AI에는 이름 대신 P1·P2 같은 임시 번호와 스킬만 보낸다.',
          '인터뷰의 "피하고 싶은 것"은 후보에서 빼는 데만 조용히 쓰고, 화면·응답 어디에도 이유로 쓰지 않는다.',
          'status=none(후보 없음)이면 alternative(대안)를 AI가 한 줄로 제안한다. 이 파트는 배치 초안에서 담당 없이 "대안으로 대신"으로 둔다.',
          'myPendingQuestions: 내가 아직 답하지 않은 추가 질문 파트 수. 단계가 team.questions일 때 1 이상이면 프론트가 9-2로 보낸다.'])
Q_SCREEN = {"partId": "prt_1", "partName": "화면 만들기", "status": "answering", "otherCandidateCount": 1,
            "questions": [{"qid": "q1", "type": "choice", "text": "비슷한 화면을 끝까지 만들어 본 적 있나요?",
                           "options": [{"value": "none", "label": "아직 없어요"}, {"value": "tutorial", "label": "수업·튜토리얼로 따라 만들어 봤어요"},
                                       {"value": "solo", "label": "혼자 기능 있는 화면을 완성해 봤어요"}, {"value": "team", "label": "팀 프로젝트에서 화면 파트를 맡아 완성했어요"}],
                           "detailLabel": "무엇을, 어떤 기술로 만들었는지 한 줄", "detailPlaceholder": "예: 동아리 행사 신청 웹 · React · 목록 필터를 맡음"},
                          {"qid": "q2", "type": "text", "text": "이 파트에서 제일 까다로운 부분을 어떻게 만들지 3줄로 적어주세요",
                           "context": "여러 곳에서 모은 공지를 **한 목록에 마감 가까운 순**으로 보여주고, **마감 하루 전**인 건 눈에 띄게 표시하기",
                           "hint": "정답을 맞히는 문제가 아니에요. 얼마나 구체적으로 그려지는지를 봐요."}],
            "answer": None}
Q_PRESENT = {"partId": "prt_3", "partName": "발표 · 시연", "status": "next", "otherCandidateCount": 1,
             "questions": [{"qid": "q1", "type": "choice", "text": "사람들 앞에서 발표나 시연을 맡아 본 적 있나요?",
                            "options": [{"value": "none", "label": "아직 없어요"}, {"value": "class", "label": "수업 발표를 해 봤어요"},
                                        {"value": "contest", "label": "공모전·해커톤에서 발표해 봤어요"}, {"value": "lead", "label": "발표와 질의응답을 주도해서 맡아 봤어요"}],
                            "detailLabel": "어떤 자리에서, 무엇을 발표했는지 한 줄", "detailPlaceholder": "예: 교내 창업 경진대회 · 5분 피칭 · 질의응답 담당"},
                           {"qid": "q2", "type": "text", "text": "처음 보는 심사위원에게 첫 30초 동안 무엇을 보여줄지 3줄로 적어주세요",
                            "context": "공지를 놓쳐 마감을 넘긴 문제를 **짧게 공감**시키고, **시연 한 장면**으로 해결을 보여주기",
                            "hint": "정답을 맞히는 문제가 아니에요. 얼마나 구체적으로 그려지는지를 봐요."}],
             "answer": None}
ep('team.questions', 'GET', '/sessions/{sessionId}/team/questions/me', 'participant', '내 추가 질문 (후보가 겹친 사람만 · 9-2)',
   '내가 후보로 겹친 파트마다 질문 2개(보기 고르기 + 한 줄, 3줄 쓰기). 겹친 파트가 없으면 items가 빈 배열.',
   res={"remainingSec": 300, "items": [Q_SCREEN, Q_PRESENT]},
   notes=['질문은 파트마다 AI 작업 12가 만든다(주제에 맞춘 context 한 줄 포함). 같은 파트의 후보들은 같은 질문을 받는다.',
          'status: answering(지금 답할 파트) · next(다음) · done(제출함). answer에는 내가 이미 낸 답(다시 열었을 때 채우기)만.',
          '다른 후보의 답·점수는 어떤 응답에도 넣지 않는다.',
          'remainingSec: 추가 질문 마감까지 남은 시간. **제한 시간은 5분 고정**(2026-09-18 결정) — team.questions 단계에 들어간 시각 + 5분. 끝나면 서버가 답한 것만으로 판단하고 team.assign으로 넘긴다(안 한 사람은 그 파트 후보에서 빠짐).'])
ep('team.answer', 'PUT', '/sessions/{sessionId}/team/questions/{partId}/answer', 'participant', '추가 질문 답 제출',
   '한 파트의 답 2개를 저장한다. 다시 보내면 덮어쓴다(마감 전까지).',
   req={"answers": {"q1": {"choice": "team", "detail": "동아리 행사 신청 웹 · React · 목록 필터와 마감 표시를 맡음"},
                    "q2": {"text": "공지마다 마감일을 날짜 값으로 저장해 두고 목록을 마감순으로 정렬해요.\n오늘과 하루 이하로 남았으면 배지를 붙여요.\n마감일이 없는 공지는 맨 아래 '마감 없음'으로 따로 묶어요."}}},
   res={"saved": True, "nextPartId": "prt_3", "remaining": 1},
   errors=[('VALIDATION', 400, '보기를 안 고름 · 3줄 답이 비어 있음 · 너무 김(q2 500자 · detail 100자)'), ('NOT_CANDIDATE', 403, '이 파트의 겹친 후보가 아님'), ('STAGE_CLOSED', 409, '추가 질문 마감 이후')],
   notes=['답 원문은 <b>본인과 AI만</b> 본다. 진행자·팀장·다른 후보에게 주는 응답에 절대 넣지 않는다.',
          '겹친 후보가 모두 답했거나(remaining 합계 0) 시간이 끝나면 AI 작업 13(누가 더 잘할지 판단)을 돌리고 단계를 team.assign으로 넘긴다(stage.changed).',
          '판단 결과는 배치표에 "추가 질문으로 정했어요"라고만 나온다. 점수·비교 문장은 저장만 하고 공개하지 않는다.'])
def part_row(pid, name, tier, assignee, method, label, **kw):
    d = {"partId": pid, "name": name, "tier": tier, "assignee": who(assignee) if assignee else None, "method": method, "methodLabel": label, "changed": False}
    d.update(kw); return d
ASSIGN = {"status": "draft", "version": 3,
          "leader": who("김승희"), "viewer": {"participantId": "par_03", "isLeader": True},
          "members": [dict(who("노형원"), counts={"core": 1, "normal": 1, "small": 0}, loadPct=70, over=False, changeFromDraft="less"),
                      dict(who("박상진"), counts={"core": 1, "normal": 0, "small": 1}, loadPct=86, over=False, changeFromDraft=None),
                      dict(who("김승희", True), counts={"core": 0, "normal": 1, "small": 2}, loadPct=84, over=False, changeFromDraft=None),
                      dict(who("이세민"), counts={"core": 1, "normal": 1, "small": 3}, loadPct=100, over=True, changeFromDraft="more")],
          "parts": [part_row("prt_1", "화면 만들기", "core", "노형원", "question", "추가 질문으로 정했어요"),
                    part_row("prt_2", "서버 · 공지 모으기", "core", "박상진", "single", "후보 1명 · 백엔드"),
                    part_row("prt_3", "발표 · 시연", "core", "이세민", "question", "추가 질문으로 정했어요", changed=True, aiAssignee=who("노형원"), marks=[who("이세민")]),
                    part_row("prt_4", "화면 디자인", "normal", "이세민", "question", "추가 질문으로 정했어요"),
                    part_row("prt_5", "발표 자료", "normal", "김승희", "single", "후보 1명 · PPT 디자인"),
                    part_row("prt_6", "기획 · 범위 관리", "normal", "노형원", "single", "후보 1명 · 서비스 기획"),
                    part_row("prt_7", "메일·LMS 자동 연동", "normal", None, "excluded", "링크 붙여넣기로 대신 · 팀 선택", alternative="링크 붙여넣기로 대신")]
                   + [part_row(pid, n, "small", a, "balance", "분량 맞추기") for pid, n, a in SMALL],
          "balance": {"note": "노형원 님에게 핵심 파트가 몰려서 작은 일은 드리지 않았어요. 작은 일 6개는 핵심 파트가 적은 사람일수록 더 맡아, 네 분의 분량이 비슷해지게 했어요.",
                      "smallTaskCounts": [{"nickname": "이세민", "count": 3, "why": "보통 파트 1개"}, {"nickname": "김승희", "count": 2, "why": "보통 파트 1개"}, {"nickname": "박상진", "count": 1, "why": "핵심 파트 1개"}]},
          "myParts": [],
          "markedByMe": [],
          "changes": [{"type": "mark", "partId": "prt_3", "partName": "발표 · 시연", "by": who("이세민")},
                      {"type": "change", "partId": "prt_3", "partName": "발표 · 시연", "from": who("노형원"), "to": who("이세민")}],
          "suggestion": {"suggestionId": "sug_1", "partId": "prt_s3", "partName": "시연용 예시 공지 만들기", "from": who("이세민"), "to": who("노형원"),
                         "reason": "발표·시연을 이세민 님이 맡으면서 이세민 님 분량이 많아졌어요. 작은 일 하나를 옮기면 다시 비슷해져요."}}
ep('team.assignment', 'GET', '/sessions/{sessionId}/team/assignment', 'participant', '배치 초안 · 분량 (9-3 모두 · 9-4 팀장)',
   '파트마다 맡은 사람과 정한 방법, 사람별 분량. 팀장이 부르면 팀원이 표시한 파트(marks) · 바꾼 내용(changes) · 옮기기 제안(suggestion)도 준다.',
   res=ASSIGN,
   notes=['method: question(추가 질문으로 정함) · single(후보 1명) · balance(작은 일 분량 맞추기) · excluded(후보 없음 → 대안으로 대신, assignee=null).',
          '<b>팀원(팀장 아님)이 부를 때</b>: marks · changes · suggestion은 null, 대신 markedByMe(내가 표시한 partId 목록)와 myParts(내 파트 이름)를 채운다. 누가 표시했는지는 팀장에게만 보인다.',
          'members[].loadPct: 가장 많은 사람 = 100 기준의 분량 막대. over=true면 "많아요"(평균보다 15% 넘게 많음), changeFromDraft="less"면 "줄었어요"(AI 초안보다 줄어듦).',
          '분량은 파트마다 AI가 추정한 작업량(effort 1~5)의 합. 핵심 파트가 몰린 사람에게는 작은 일을 주지 않는 방식으로 맞춘다(AI 작업 14).',
          'changed=true면 팀장이 AI 초안과 다르게 바꾼 파트, aiAssignee는 원래 초안 담당.',
          'suggestion: 분량이 한쪽으로 쏠렸을 때(over) 그 사람의 <b>작은 일</b> 하나를 가장 여유 있는 사람에게 옮기자는 제안 1개. 쏠린 사람이 작은 일을 하나도 안 맡았거나 팀장이 "그대로 둘게요"를 누른 제안이면 null.',
          '바뀔 때마다 version을 올리고 team.assignment.updated 이벤트를 보낸다.'])
ep('team.mark', 'PUT', '/sessions/{sessionId}/team/parts/{partId}/mark', 'participant', '이야기해 볼 파트 표시 · 해제 (9-3)',
   '회의에서 바꾸고 싶은 파트를 표시한다. 팀장 화면(9-4)의 "회의에서 바꾼 것"에 모인다.',
   req={"marked": True}, res={"partId": "prt_3", "marked": True},
   errors=[('STAGE_CLOSED', 409, '배치 확정 이후')],
   notes=['누가 표시했는지는 팀장에게만 보인다(다른 팀원에게는 비공개).', '표시하면 team.assignment.updated 이벤트(팀장 화면 갱신).'])
ep('team.reassign', 'PUT', '/sessions/{sessionId}/team/parts/{partId}/assignee', 'leader', '맡은 사람 바꾸기 (팀장 · 9-4)',
   '회의에서 말로 정한 대로 파트의 담당을 바꾼다. 분량·쏠림 제안을 다시 계산해서 배치 전체를 돌려준다.',
   req={"participantId": "par_02"}, res=ASSIGN,
   errors=[('NOT_LEADER', 403, '팀장이 아님'), ('VALIDATION', 400, '이 세션 참가자가 아닌 participantId · 후보 없음(excluded) 파트')],
   notes=['AI 초안 담당과 같아지면 changed=false로 되돌린다.',
          '배치 확정(team.confirm) 뒤에도 팀장은 이 API로 담당을 고칠 수 있다 → 보고서의 파트·워크플로우를 다시 만들고 report.ready 이벤트(보고서 수정 화면 디자인은 아직 없음).'])
ep('team.suggestion', 'POST', '/sessions/{sessionId}/team/suggestions/{suggestionId}', 'leader', '옮기기 제안 받기 · 그대로 두기 (팀장)',
   '"옮기기"면 제안대로 작은 일의 담당을 바꾸고, "그대로 둘게요"면 제안만 닫는다.',
   req={"accept": True}, res=ASSIGN,
   errors=[('NOT_LEADER', 403, '팀장이 아님'), ('SUGGESTION_STALE', 409, '그 사이 배치가 바뀌어 제안이 더 이상 맞지 않음 → 프론트는 다시 불러오기')])
ep('team.revert', 'POST', '/sessions/{sessionId}/team/assignment/revert', 'leader', 'AI 초안으로 되돌리기 (팀장)',
   '팀장이 바꾼 담당을 모두 AI 초안으로 되돌린다. 팀원 표시(marks)는 남긴다.', req={}, res=ASSIGN,
   errors=[('NOT_LEADER', 403, '팀장이 아님'), ('ASSIGNMENT_CONFIRMED', 409, '이미 확정됨')])
ep('team.confirm', 'POST', '/sessions/{sessionId}/team/assignment/confirm', 'leader', '배치 확정 → 보고서 만들기 (팀장)',
   '지금 배치를 확정하고 보고서 단계로 넘긴다. 모두의 화면이 보고서(9-5)로 이동한다.',
   req={"version": 3}, res={"status": "confirmed", "reportReady": False, "stage": {"id": "report", "label": "파트 나누기 · 보고서", "subStep": 6, "progress": 100}},
   errors=[('NOT_LEADER', 403, '팀장이 아님'), ('VERSION_MISMATCH', 409, '보고 있던 배치가 최신이 아님(그 사이 바뀜) → 다시 불러온 뒤 확정'), ('ASSIGNMENT_CONFIRMED', 409, '이미 확정됨')],
   notes=['요청의 version이 서버 배치 version과 다르면 409 (다른 창에서 바꾼 걸 모르고 확정하는 것 방지).',
          '확정하면 team.confirmed + stage.changed(report) 이벤트, AI 작업 15(보고서 요약·워크플로우)를 시작. 끝나면 report.ready.',
          '세션을 끝난 상태(status=ended)로 바꾸고 지난 세션 기록(A4)의 reportAvailable=true.'])
REPORT = {"ready": True, "reportId": "rep_7K2X9", "sessionId": SID, "version": 1, "createdAt": "2026-09-18T16:10:00+09:00",
          "meta": {"date": "2026-09-18", "memberCount": 4, "durationMin": 70, "sessionTopic": "교내 해커톤 서비스 아이디어"},
          "topic": {"title": "과제 공지와 마감을 한곳에 모아 알려주는 웹", "summary": "메일·학교 사이트·단톡에 흩어진 과제 공지와 마감을 한 화면에 모아 알려줘요.", "owner": {"nickname": "노형원", "rank": 1}},
          "why": {"votes": {"total": 8, "top": 3, "gapToSecond": 1},
                  "review": {"grade": "go", "summary": "일정 앱은 많지만 여러 곳의 학교 공지를 모아주는 건 드물어요", "searchUrl": "https://search.example.com/?q=..."},
                  "praise": {"count": 2, "points": ["다들 겪는 문제라 공감이 커요", "발표하기 쉬워요"]},
                  "thread": '팀플에서 "누가 무엇을 했는지"가 한곳에 남지 않는 문제와 이어져요 (3위 아이디어도 같은 뿌리)'},
          "feasibility": {"level": "상", "summary": "웹 화면 2명 · 백엔드 1명으로 만들 수 있어요",
                          "missingSkills": [{"name": "메일·LMS 자동 연동", "decision": "이번 범위에서 빼고 링크 붙여넣기로 대신"}],
                          "scope": "핵심 기능은 공지 모으기 · 마감 알림 두 가지로 시작해요"},
          "votes": {"maxVotesPerPerson": 2, "ranks": [{"rank": 1, "title": "과제 공지와 마감을 한곳에 모아 알려주는 웹", "owner": "노형원", "votes": 3},
                                                      {"rank": 2, "title": "관심 있는 학교 행사·특강 소식만 골라 알려주는 웹", "owner": "김승희", "votes": 2},
                                                      {"rank": 3, "title": "회의 후 할 일 정리 · 열람실 빈자리 제보판 · 학과 중고 전공책", "owner": None, "tieCount": 3, "votes": 1}]},
          "parts": {"leader": "김승희",
                    "core": [{"name": "화면 만들기", "assignee": "노형원"}, {"name": "서버 · 공지 모으기", "assignee": "박상진"}, {"name": "발표 · 시연", "assignee": "이세민"}],
                    "normal": [{"name": "화면 디자인", "assignee": "이세민"}, {"name": "발표 자료", "assignee": "김승희"}, {"name": "기획 · 범위 관리", "assignee": "노형원"}],
                    "small": [{"name": "경쟁 서비스 조사", "assignee": "이세민"}, {"name": "시연용 예시 공지 만들기", "assignee": "노형원"}, {"name": "기능 테스트 · 버그 기록", "assignee": "이세민"},
                              {"name": "사용자 인터뷰 3명", "assignee": "김승희"}, {"name": "제출 문서 · 보고서 정리", "assignee": "김승희"}, {"name": "회의록 · 일정 챙기기", "assignee": "박상진"}],
                    "excluded": [{"name": "메일·LMS 자동 연동", "alternative": "링크 붙여넣기로 대신"}]},
          "workflow": {"stages": [
              {"no": 1, "name": "범위와 설계 정하기", "current": True, "make": "핵심 기능 2개의 화면 흐름 · 공지를 가져올 게시판 3곳",
               "tasks": [{"nickname": "노형원", "text": "기능 범위와 화면 흐름 정리", "lead": "이끌기"}, {"nickname": "박상진", "text": "게시판 3곳에서 글을 가져올 수 있는지 확인", "lead": None},
                         {"nickname": "김승희", "text": "사용자 인터뷰 3명으로 불편 확인", "lead": None}, {"nickname": "이세민", "text": "경쟁 서비스 조사해서 공유", "lead": None}],
               "handoffs": ["화면 흐름 노형원 → 이세민", "가져올 수 있는 게시판 박상진 → 노형원"]},
              {"no": 2, "name": "만들기", "current": False, "make": "공지 목록 · 마감 알림이 동작하는 웹",
               "tasks": [{"nickname": "노형원", "text": "공지 목록·마감 표시 화면 · 시연용 예시 공지", "lead": "이끌기 · 화면"}, {"nickname": "박상진", "text": "공지 모으기 · 알림 보내기", "lead": "이끌기 · 서버"},
                         {"nickname": "이세민", "text": "화면 디자인 · 발표 흐름 초안", "lead": None}, {"nickname": "김승희", "text": "발표 자료 틀 · 서비스 이름 정하기", "lead": None}],
               "handoffs": ["화면 디자인 이세민 → 노형원", "공지 데이터 형식 박상진 ↔ 노형원"]},
              {"no": 3, "name": "합치고 확인하기", "current": False, "make": "처음부터 끝까지 시연되는 버전",
               "tasks": [{"nickname": "노형원", "text": "화면과 서버 연결 (박상진과 함께)", "lead": None}, {"nickname": "박상진", "text": "서버 연결 · 시연 환경 준비", "lead": None},
                         {"nickname": "이세민", "text": "기능 테스트 · 버그 기록", "lead": "이끌기"}, {"nickname": "김승희", "text": "인터뷰 결과를 발표 자료에 반영", "lead": None}],
               "handoffs": ["버그 목록 이세민 → 노형원 · 박상진"]},
              {"no": 4, "name": "발표 준비", "current": False, "make": "발표 자료 · 시연 · 제출 문서",
               "tasks": [{"nickname": "이세민", "text": "발표 흐름 · 시연 연습", "lead": "이끌기 · 발표"}, {"nickname": "김승희", "text": "발표 자료 완성 · 제출 문서 정리", "lead": "이끌기 · 자료"},
                         {"nickname": "노형원", "text": "시연 화면 점검 · 리허설 피드백", "lead": None}, {"nickname": "박상진", "text": "시연 환경 최종 점검", "lead": None}],
               "handoffs": ["발표 자료 김승희 → 이세민"]}],
              "always": [{"text": "회의록 · 일정 챙기기", "nickname": "박상진"}, {"text": "기능 범위 지키기", "nickname": "노형원"}]},
          "anonymous": ["댓글 쓴 사람", "누가 어디에 투표했는지", "인터뷰 답 원문", "추가 질문의 답"]}
ep('report.get', 'GET', '/sessions/{sessionId}/report', 'participant', '최종 보고서 (9-5 · A4 보고서 보기)',
   'A4 2쪽 보고서에 들어갈 내용 전부. 1쪽 = 왜 이 주제인지 · 현실성 · 투표 결과 · 파트와 맡은 사람, 2쪽 = 팀 워크플로우 4단계 · 내내 하는 일.',
   res=REPORT,
   errors=[('NOT_PARTICIPANT', 403, '이 세션 참가자가 아님')],
   notes=['AI 작업 15가 끝나기 전에는 {"ready": false} → 끝나면 report.ready 이벤트.',
          '세션이 끝난 뒤에도 그 세션 참가자였던 회원은 계속 볼 수 있다(지난 세션 기록 A4의 "보고서 보기").',
          '공유 링크는 만들지 않는다(2026-09-18 결정) — 보고서는 참가자가 9-5 · A4에서 보거나 PDF로 저장해서 나눈다. 응답에 shareUrl 없음.',
          '"PDF로 저장"은 프론트가 브라우저 인쇄(A4)로 만든다 — 서버 PDF 생성은 필요 없음.',
          '익명 규칙: 아이디어 주인·파트 담당 이름은 보여주지만 anonymous 목록의 정보(댓글 작성자·투표자·인터뷰 원문·추가 질문 답)는 절대 넣지 않는다.',
          '워크플로우의 할 일·넘겨주기는 AI 초안이다. 검색 결과가 근거인 부분(searchUrl)만 링크를 단다.'])

ENDPOINTS = {e['id']: e for e in E}

# ───────── 실시간 이벤트 ─────────
EVENTS = [
    ('participant.joined', '대기실', '{"participantId":"par_04","nickname":"박상진","role":"participant"}', '참여자 줄 추가, "3 / 4" 숫자 갱신'),
    ('participant.left', '대기실', '{"participantId":"par_04"}', '접속 점 끄기(나간 게 아니라 끊긴 것일 수도 있음)'),
    ('participant.online', '대기실', '{"participantId":"par_04","online":true}', '재접속한 사람 접속 점 다시 켜기'),
    ('participant.kicked', '대기실(내보내진 사람)', '{"participantId":"par_04"}', '내보내진 사람은 랜딩으로'),
    ('session.started', '대기실', '{"stage":{"id":"icebreak","progress":3},"timer":{"endsAt":"…"}}', '모두 7-1 (진행자도 인터뷰 · 끝나면 7-6)'),
    ('stage.changed', '모든 세션 화면', '{"stage":{"id":"diverge.comment","label":"아이디어 발산","subStep":3,"progress":35}}', '해당 단계 화면으로 이동, 상단바 갱신'),
    ('timer.sync', '모든 세션 화면', '{"endsAt":"2026-09-18T15:30:00+09:00","serverNow":"…"}', '1분마다 서버 시각 기준으로 타이머 보정'),
    ('icebreak.progress', '7-1~7-6', '{"nickname":"김승희","step":3,"done":false}', '"팀 진행" 카드 한 줄 갱신'),
    ('icebreak.news.ready', '7-1', '{"ready":true}', '질문 2 카드 불러오기'),
    ('icebreak.groups.updated', '7-6 (진행자)', '{"newMaterials":2}', '"새 재료 2개 · 다시 묶기" 안내'),
    ('ideas.submitted', '8-1, 8-2', '{"submittedCount":3,"memberCount":4}', '제출 인원 갱신'),
    ('comments.progress', '8-4', '{"doneCount":2,"memberCount":4}', '진행 인원 갱신'),
    ('reviews.ready', '8-4 → 8-5', '{"ready":true}', 'AI 검증 목록 불러오기'),
    ('vote.progress', '8-6', '{"votedCount":3,"memberCount":4}', '"투표한 사람 3 / 4" 갱신'),
    ('vote.closed', '8-6, 8-6w, 8-7', '{}', '모두 8-7로 (진행자는 확정 버튼, 참가자는 보기 전용)'),
    ('topic.confirmed', '8-7 이후', '{"ideaId":"ide_c1","title":"…","leader":{"participantId":"par_03","nickname":"김승희"}}', '파트 나누기(9-1)로'),
    ('team.parts.ready', '9-1', '{"ready":true}', '파트·후보 목록 불러오기 (AI 파트 나누기 끝)'),
    ('team.assignment.updated', '9-3 · 9-4', '{"version":4}', '배치 초안 다시 불러오기 (팀장이 바꿈 · 팀원이 표시함)'),
    ('team.confirmed', '9-3 · 9-4', '{"reportReady":false}', '보고서(9-5)로 이동'),
    ('report.ready', '9-5', '{"ready":true}', '보고서 불러와서 A4 2쪽 그리기'),
]

ERRORS = [
    ('VALIDATION', 400, '입력값이 규칙에 맞지 않음. details에 필드별 이유'),
    ('UNAUTHORIZED', 401, '액세스 토큰 없음/만료 → 프론트가 /auth/refresh 한 번 시도 후 실패하면 로그인(A1)으로'),
    ('REFRESH_INVALID', 401, '리프레시 토큰 없음·만료·재사용 → 로그인(A1)으로'),
    ('INVALID_CREDENTIALS', 401, '이메일·비밀번호 틀림'),
    ('PASSWORD_MISMATCH', 403, '로그인한 사람의 비밀번호 확인 실패 (이메일 · 비밀번호 변경, 탈퇴) — 401이 아니라서 프론트가 로그인 유지 재시도를 하지 않음'),
    ('FORBIDDEN', 403, '권한 없음(예: 진행자 전용 API를 참가자가 호출)'),
    ('PLAN_LIMIT', 403, '무료 요금제 한도 초과 → 프론트는 Pro 안내'),
    ('OWN_IDEA', 403, '내 아이디어에 댓글'),
    ('KICKED', 403, '이 세션에서 내보내진 사람'),
    ('NOT_PARTICIPANT', 403, '이 세션 참가자가 아님'),
    ('SESSION_NOT_FOUND', 404, '없는 방 코드/세션'),
    ('NOT_FOUND', 404, '이 세션에 없는 id (아이디어 · AI 아이디어 · 숨은 공통점 등)'),
    ('EMAIL_TAKEN', 409, '이미 가입된 이메일'),
    ('SESSION_FULL', 409, '방 인원이 가득 참'),
    ('SESSION_STARTED', 409, '이미 시작한 방에 새로 입장 (재접속은 허용)'),
    ('PROFILE_REQUIRED', 409, '프로필을 만들지 않은 회원이 세션 만들기/입장 → 프로필 만들기(3)로'),
    ('STAGE_MISMATCH', 409, '화면이 보고 있던 단계와 서버 단계가 다름(중복 클릭 등) → 프론트는 session.get으로 다시 맞춤'),
    ('STAGE_LOCKED', 409, '이 단계에서는 넘기기·되돌리기를 할 수 없음 (대기실 → 세션 시작, 투표 결과 → 주제 확정으로만)'),
    ('NOT_ALL_SUBMITTED', 409, '아직 제출(아이디어 · 댓글)을 안 한 사람이 있어서 넘길 수 없음 → 진행자는 기다리거나 force=true'),
    ('STAGE_CLOSED', 409, '이미 지난 단계의 제출'),
    ('PRAISE_LIMIT', 409, '좋은 점 2개 초과'),
    ('VOTE_LIMIT', 409, '2표 초과'),
    ('TOO_MANY_ATTEMPTS', 429, '요청 횟수 제한'),
    ('NOT_CANDIDATE', 403, '추가 질문 대상(겹친 후보)이 아님'),
    ('NOT_LEADER', 403, '팀장만 할 수 있는 동작(담당 바꾸기 · 확정)'),
    ('PARTS_NOT_READY', 409, '파트 나누기 AI 작업이 아직 안 끝남'),
    ('ASSIGNMENT_CONFIRMED', 409, '이미 확정된 배치'),
    ('VERSION_MISMATCH', 409, '보고 있던 배치가 최신이 아님 → 다시 불러온 뒤 확정'),
    ('SUGGESTION_STALE', 409, '옮기기 제안이 더 이상 맞지 않음'),
    ('AI_UNAVAILABLE', 503, 'AI/검색 서비스 일시 장애 → 프론트는 "잠시 후 다시" 안내'),
]
