# 3차 전달 문서 내용 — 담당: 친구 (친구의 Claude)
# · 이 파일의 SPEC만 채우면 docs/{파일}이 만들어진다 (모양은 _generator/ho_phase1.py = 1차 문서와 같음)
# · 검사/미리보기: python _generator/check_delivery.py 3   → 문제 0건이 되면 READY = True
# · 진짜 생성: python _generator/handoff.py  (READY=True + 검사 통과일 때만 docs/ 에 씀)
# · 문장 규칙: 표 칸(why · scenarios)에는 줄바꿈·| 금지(<br> 사용) · 에러는 "409 STAGE_MISMATCH"처럼 HTTP 번호와 코드를 같이
# · 3단 이벤트 이름(icebreak.news.ready · icebreak.groups.updated)은 검사기 allow_words 로 예외 처리 (합쳐진 검사기 기준)
READY = True

SPEC = dict(
    allow_words=['icebreak.news', 'icebreak.groups'],
    phase='3차',
    title='백엔드 3차 전달 — 화면 7-1 ~ 7-7 (아이스브레이킹 · AI 인터뷰 · 재료)',
    intro='이번에 만들 범위와 **끝났다고 볼 수 있는 기준**이에요. 화면 폴더: `screens/07-1-icebreak-q1-discomfort` ~ `screens/07-5-icebreak-q5-wrapup` (참가자 인터뷰), `screens/07-6-icebreak-host` (진행자), `screens/07-7-diverge-materials` (발산 첫 화면의 재료). 채팅 공통 코드는 `assets/js/icebreak-chat.js` (각 README에 화면 설명).',
    rules=[
        '**AI와 1:1 인터뷰, 답 원문은 본인만** — 질문 5개는 순서가 고정이에요. 답 원문은 `ice.state`(본인)에만 들어가고, 진행자·팀원이 부르는 어떤 API·이벤트에도 원문·작성자를 넣지 않아요. 재료는 이름 없이 "몇 명이 말했는지"(count)만.',
        '**꼬리질문은 질문당 최대 1번** — 답이 짧거나 모호하면 AI(가벼운 모델, AI 작업 1)가 꼬리질문을 1번 해요. 꼬리질문에 또 짧게 답해도 다음 질문으로 넘어가요. `ice.skip`은 지금 질문(꼬리질문 포함)을 건너뛰고 다음 질문을 줘요.',
        '**소식 카드는 세션 시작 직후 미리** — `session.start`(2차) 때 AI 작업 2(검색 + 요약)를 뒤에서 시작해 세션 단위로 캐시해요. 준비되면 세션 전원에게 `icebreak.news.ready`를 1번 보내요. 검색이 안 되면 `ice.news`가 `{"ready": true, "cards": [], "fallback": true}` → 질문 2·3은 건너뛰고 질문 1 다음이 질문 4(step 4).',
        '**진행자도 참가자와 똑같이 인터뷰해요** — 세션이 시작되면 진행자도 7-1로 가서 질문 5개에 답하고, 끝나면 "진행자 화면으로 →" 링크로 7-6에 가요. 진도 · 재료 · 인원 수(`memberCount`) 모두 진행자를 포함해요.',
        '**재료 뽑기(AI 작업 4)는 한 사람이 끝날 때, 묶기(AI 작업 5)는 진행자가 요약(7-6)을 열 때** — 전원이 끝나길 기다리지 않아요(늦은 사람은 아래 이벤트로). 늦게 끝난 사람 재료는 `icebreak.groups.updated`로 알리고 진행자가 "다시 묶기"를 눌러야 반영돼요. 재료는 빼거나 지우지 않아요.',
        '**발산 시작 = 인터뷰 마감** — 진행자가 `session.advance`(2차, from: icebreak)로 넘기면 서버는 단계를 `diverge.write`로 저장하고: 아직 안 끝난 인터뷰는 그대로 닫고(그 사람 답까지만 재료로 뽑기), 이후 `ice.send`·`ice.skip`은 `409 STAGE_CLOSED`. 재료 묶음은 그 시점 것으로 확정해 `ice.materials`로 발산에 넘겨요. 아이스브레이킹에서 대기실로 되돌리기는 없어요(`session.back`은 `409 STAGE_LOCKED`).',
        '**중복 · 재접속** — `ice.send`의 `clientMessageId`가 같으면 새 메시지를 만들지 않고 이전 응답을 그대로 돌려줘요. 새로고침 · 재접속은 `ice.state`로 대화와 질문 번호를 복구해요(화면이 이 응답으로 대화를 다시 그려요).',
    ],
    rules_after='단계 순서와 익명 규칙은 [01-백엔드-한눈에-보기.md](01-백엔드-한눈에-보기.md)의 "4. 세션 단계"와 "5. 익명 규칙", AI 작업 1~5번은 [05-AI-작업-목록.md](05-AI-작업-목록.md), 공통 형식은 [02-API-공통-규칙.md](02-API-공통-규칙.md).',
    api_intro='참가자 화면(7-1~7-5)이 부르는 건 send · skip · news · react · explain · myMaterials, 진행자(7-6)는 overview · regroup · focus, 발산 첫 화면(7-7)은 materials예요. state · progress는 화면이 아직 안 부르지만 새로고침 복구와 "팀 진행" 카드의 첫 그리기에 필요해서 함께 넣었어요. **2차(대기실 · 단계 넘기기 · 실시간)가 끝난 서버** 위에 얹는 범위예요.',
    ids=[
        'ice.state',
        'ice.send',
        'ice.skip',
        'ice.news',
        'ice.react',
        'ice.explain',
        'ice.progress',
        'ice.myMaterials',
        'ice.overview',
        'ice.regroup',
        'ice.focus',
        'ice.materials',
    ],
    why={
        'ice.state': '7-1~7-5 화면을 열 때 대화 · 질문 번호 복구 (새로고침 · 재접속)',
        'ice.send': '7-1~7-5 보내기 / Enter',
        'ice.skip': '7-1~7-5 "넘어가기"',
        'ice.news': '7-2 소식 카드 3장 (화면이 이 응답으로 카드를 그림)',
        'ice.react': '7-2 카드 반응 (처음 들어요 · 들어봤어요 · 잘 알아요)',
        'ice.explain': '7-2 "이게 뭐예요?" 뜻풀이',
        'ice.progress': '7-1~7-6 "팀 진행" 카드 처음 그리기 (그 뒤는 icebreak.progress 이벤트)',
        'ice.myMaterials': '7-5 내 재료 목록 (실서버 모드에서 다시 그림)',
        'ice.overview': '7-6 진행자 화면 전체 (진도 · 소식 반응 · 재료 묶음)',
        'ice.regroup': '7-6 "다시 묶기"',
        'ice.focus': '7-6 "먼저 보기" 토글',
        'ice.materials': '7-7 발산 재료 패널 (먼저 보기 묶음 · 나머지)',
    },
    events_intro='3차가 맡는 실시간 이벤트는 아래 3개예요. `stage.changed`(2차)는 7-1~7-5가 `diverge.write`를 받으면 8-1로 자동 이동하는 데 써요 (7-6 · 7-7에는 처리가 없어서 새로고침 때 `session.get`으로 이동). 이벤트에도 익명 규칙이 똑같이 적용돼요 — 진도·인원 수만, 답 내용은 넣지 않아요.',
    events=[
        ('icebreak.progress', '"팀 진행" 카드에서 닉네임이 같은 줄을 "n / 5" 또는 "완료"로 갱신 (줄은 HTML 예시 이름이라 다른 닉네임이면 갱신 안 됨)'),
        ('icebreak.news.ready', '7-1이면 7-2로 이동 (7-2가 열릴 때 ice.news로 카드를 그림). 7-2~7-5에서 받으면 아무 일도 없음'),
        ('icebreak.groups.updated', '진행자 7-6에 토스트 "새 재료 N개가 들어왔어요 · 다시 묶기로 반영해요"'),
    ],
    done_intro='프론트의 `assets/js/config.js`에서 `useMock: false`, `baseUrl`을 서버 주소로 바꾸고 확인해요. **2차(대기실 · 단계 넘기기 · 실시간)가 끝난 서버** 기준이에요.<br>사람마다 **다른 브라우저 프로필**(또는 다른 브라우저)로 로그인해요 — 같은 프로필의 창끼리는 로그인 정보가 섞여요.<br>화면에 아직 버튼이 없거나 서버 데이터를 아직 그리지 않는 동작은, 그 사람 창의 개발자도구 **콘솔에서 `await api.call(…)`** 로 부르거나 **Network 탭의 응답**으로 확인해요.<br>진행자 1명 + 참가자 2명 이상(4명 권장)으로 방을 만들고 "세션 시작"을 누른 뒤 확인해요. 진행자도 7-1로 가서 인터뷰를 하고, 끝나면 대화창 마지막의 "진행자 화면으로 →" 링크로 7-6에 가요. 인터뷰 시나리오는 진행자 · 참가자 창 모두에서 확인해요.',
    scenarios=[
        ('참가자가 7-1에서 구체적인 답을 보내기', '다음 질문 말풍선(label "질문 2 · …")이 오고 상단 "2 / 5"와 진행 막대 갱신 · 오른쪽 "오늘 나눌 이야기" 2번이 현재로'),
        ('짧거나 모호한 답(예: "과제")을 보내기', '꼬리질문 말풍선 1개(label "꼬리질문", style `fq`) · `step`은 그대로 1'),
        ('꼬리질문에 또 짧게 답하기', '두 번째 꼬리질문 없이 질문 2로 넘어감 (질문당 최대 1번)'),
        ('"넘어가기"(`ice.skip`)', '지금 질문(꼬리질문 중이어도)을 건너뛰고 다음 질문 말풍선 · `step` +1'),
        ('같은 `clientMessageId`로 `ice.send`를 두 번 (콘솔에서 재전송)', '두 번째는 이전 응답 그대로 · `ice.state` 응답의 messages에 내 답이 1개만'),
        ('질문 5까지 답하기', '`done: true` + 끝 안내 말풍선(style `good`) 1개 · 입력칸 비활성("인터뷰가 끝났어요") · 상단 "완료"'),
        ('인터뷰가 끝난 사람이 콘솔에서 `ice.send` 또는 `ice.skip`', '409 INTERVIEW_DONE · 대화는 그대로'),
        ('세션 시작 뒤 소식 카드가 준비됨 (뒤에서 검색 + 요약)', '7-1에 있던 사람은 `icebreak.news.ready`를 받고 7-2로 이동 · `ice.news` 응답 `ready: true`, 카드 3장(시장·기술·규제)에 `plain`·`forTeam`·출처 `url`·`publishedAt` · 모든 참가자가 같은 카드'),
        ('검색이 안 되는 상태로 세션 시작 (검색 API 키를 빼고 테스트)', '`ice.news` 응답 `{"ready": true, "cards": [], "fallback": true}` · 질문 1 다음 말풍선이 질문 4(`step: 4`) · `icebreak.news.ready`는 안 옴'),
        ('7-2 카드에서 "들어봤어요" 누르기 → 다시 "잘 알아요"', '`ice.react` 응답 `myReaction: "heard"` → `"know"`로 바뀜 · 새로고침 후 `ice.news`의 `myReaction`에 남아 있음 (카드 id가 `news_1`~`news_3`이 아니면 콘솔로)'),
        ('없는 cardId로 `ice.react` · `ice.explain` / 없는 반응 값 / 없는 groupId로 `ice.focus`', '404 NOT_FOUND / 400 VALIDATION / 404 NOT_FOUND (message에 이유)'),
        ('7-2 "이게 뭐예요?"', '하늘색 뜻풀이 말풍선(style `explain`) 추가 · 오른쪽 "내가 물어본 말"에 단어가 쌓임(`askedTerms`) · 같은 단어를 다시 물어도 목록에 1번만'),
        ('AI가 응답하지 못할 때 뜻풀이 / 답 보내기', '503 AI_UNAVAILABLE → 토스트 · 대화는 그대로 (답 보내기는 꼬리질문 판단 없이 다음 질문으로 가도 됨)'),
        ('한 사람이 뜻풀이·답 보내기를 짧은 시간에 여러 번', '429 TOO_MANY_ATTEMPTS (사람당 횟수 제한) → 토스트'),
        ('한 사람이 답할 때마다 다른 참가자의 7-1과 진행자의 7-6', '`icebreak.progress`로 그 닉네임 줄이 "n / 5" → 끝나면 "완료" (예시 이름과 다르면 이벤트 payload로 확인) · 이벤트에 답 내용 없음'),
        ('7-5(질문 5 끝)에서 화면 열기', '`ice.myMaterials`로 내 재료 목록이 다시 그려짐 · "피할 것"은 회색 태그 · 삭제 버튼 없음'),
        ('7-1~7-5에서 새로고침', '`session.get`으로 7-1에 남고 `ice.state` 응답에 지금까지 대화(`messages`) · `step` · `done` (화면은 아직 예시 대화 → 응답으로 확인)'),
        ('**익명**: 참가자 계정으로 `ice.progress`', '응답 items에 `nickname` · `isMe` · `step` · `done`만 · 답 원문 없음 · 진행자도 한 줄로 들어 있음(자기 인터뷰 진도)'),
        ('**익명**: 진행자 계정으로 `ice.overview`', '`progress`는 닉네임+진도만 · `newsReactions`는 인원 수(`counts`)만 · `groups[].items`는 `text` · `count` · `avoid`만 — **답 원문 · 누가 말했는지 없음** · `hint`도 인원 수로만'),
        ('참가자 계정으로 `ice.overview` · `ice.regroup` · `ice.focus`', '403 FORBIDDEN'),
        ('진행자 7-6 "먼저 보기" 토글 켜기/끄기', '`ice.focus` 응답 `{"groupId", "focus"}` · `ice.materials`의 `focusGroups`/`otherGroups`에 바로 반영 (묶음 id가 `grp_1`~이 아니면 콘솔로)'),
        ('진행자 7-6 "다시 묶기"', '토스트 "재료를 다시 묶었어요" · `ice.regroup` 응답 `groups`가 새로 만들어지고 먼저 보기 표시는 비슷한 그룹에 이어짐 · 재료 개수는 줄지 않음'),
        ('진행자가 요약을 연 뒤에 늦게 끝난 참가자의 인터뷰가 끝남', '진행자에게 `icebreak.groups.updated` → 토스트 "새 재료 N개…" · `ice.overview`는 다시 묶기 전까지 그대로'),
        ('진행자가 질문 5까지 답하기', '끝 안내 말풍선 아래 "진행자 화면으로 가서 팀 재료 보기 →" 링크 → 누르면 7-6 · 7-6 진도 목록에 진행자 줄이 "완료"'),
        ('진행자 7-6 "이전 단계"', '409 STAGE_LOCKED 토스트 (아이스브레이킹 → 대기실 되돌리기 없음)'),
        ('진행자 7-6 "발산 시작"', '`session.advance` → 단계 `diverge.write` 저장 → `stage.changed` → 7-1~7-5의 참가자는 8-1로 자동 이동 · 진행자는 7-7'),
        ('발산 시작 뒤 아직 답하던 참가자가 답을 보내기', '409 STAGE_CLOSED 토스트 · 그 사람 재료는 답한 데까지만 뽑혀 `ice.materials`에 포함'),
        ('7-7 · 8-1에서 콘솔로 `ice.materials`', '`total` · `focusGroups`(먼저 보기) · `otherGroups` — 이름·출처 없음 · 발산 시작 시점 묶음으로 고정(이후 `ice.regroup`은 409 STAGE_CLOSED)'),
    ],
    extra_sections=[
        ('이번 범위의 경계', '\n'.join([
            '- 방 만들기 · 대기실 · **세션 시작 · 단계 넘기기 · WebSocket 연결 자체는 2차**예요. 3차는 그 위에서 `icebreak` 단계 안의 일만 다뤄요. 세션 시작 직후 소식 카드 작업을 시작하는 것과, `icebreak`를 떠날 때 인터뷰를 마감하는 것은 3차가 맡아요.',
            '- 재료가 발산에서 어떻게 쓰이는지(8-1 제출 · 익명 순위표)는 **4차**예요. 3차는 `ice.materials`까지.',
            '- 7-7의 입력칸(아이디어 한 줄)은 브라우저에 초안으로만 저장하고 서버로 보내지 않아요 → 4차 `idea.submit`.',
            '- 재료를 쓰는 AI 추천(8-2) · 숨은 공통점(8-6)은 **5차**예요.',
        ])),
        ('확인이 필요한 것', '\n'.join([
            '자세한 내용과 제안은 `_작업메모/친구-확인요청.md`에 있어요. 이 문서는 제안대로 쓴 상태예요.',
            '',
            '1. **[프론트] 7-1은 `icebreak.news.ready`를 받을 때만 7-2로 이동** — 카드가 이미 준비된 뒤 질문 2에 도달한 사람은 7-1에 남은 채 질문 2 문장만 받아요. 서버는 이벤트를 세션 전원에게 1번만 보내면 되고, 그 뒤에 온 사람은 프론트가 `ice.news`의 `ready`로 확인해야 해요(프론트 남은 일).',
            '2. **[명세] `ice.send` · `ice.skip`에 발산 시작 뒤(409 STAGE_CLOSED)와 `ice.skip`의 인터뷰 끝(409 INTERVIEW_DONE)이 없음** — 이 문서는 그렇게 동작한다고 썼어요.',
            '3. **[명세] 검색 실패(fallback) 때 step 번호** — 질문 2·3을 건너뛰면 `step: 4`로 보내는 것으로 썼어요(프론트는 값을 그대로 "n / 5"로 표시).',
            '4. **[명세] 없는 cardId · groupId** — 공통 코드 404 NOT_FOUND, 없는 반응 값은 400 VALIDATION으로 썼어요.',
            '5. **[결정됨 2026-09-18] 진행자도 인터뷰** — 프론트 · 문서에 반영했어요(단계 → 화면 표 · 5 대기실 · 7-5 링크).',
            '6. **[디자인] 7-6 "이전 단계"는 항상 409 STAGE_LOCKED** — 2차 문서에도 적혀 있어요.',
        ])),
    ],
    front_title='프론트 쪽 참고 (이미 구현된 것 · 아직 안 된 것)',
    front=[
        '채팅 공통 — 보내기·Enter(`ice.send`, `clientMessageId` 포함) · 넘어가기(`ice.skip`) · 응답 `messages`를 말풍선으로, `step`·`done`으로 "n / 5"와 막대 · `icebreak.progress`로 팀 진행 줄 갱신 · `stage.changed`가 `diverge.write`면 8-1로: `assets/js/icebreak-chat.js`',
        '7-1 `icebreak.news.ready` → 7-2로 이동: `screens/07-1-icebreak-q1-discomfort/screen.js`',
        '7-2 카드 반응(`ice.react`) · 뜻풀이(`ice.explain`) — 카드 id는 화면 순서대로 `news_1`~`news_3`을 붙여서 부름: `screens/07-2-icebreak-q2-news/screen.js`',
        '7-5 내 재료 다시 그리기(`ice.myMaterials`, 실서버 모드) · 입력칸 비활성: `screens/07-5-icebreak-q5-wrapup/screen.js`',
        '7-6 먼저 보기(`ice.focus`, 묶음 id는 화면 순서대로 `grp_1`~) · 다시 묶기(`ice.regroup`) · 이전 단계(`session.back`) · 발산 시작(`session.advance` → 7-7) · 진도·새 재료 이벤트: `screens/07-6-icebreak-host/screen.js`',
        '세션 화면 공통 — 열릴 때 `session.get`으로 단계 확인 후 다른 단계면 이동, 401이면 refresh 후 재시도, 에러는 `message`를 토스트로: `assets/js/app.js` · `assets/js/api.js`',
        '**아직 안 된 것** — `ice.state` · `ice.progress` · `ice.news` · `ice.overview` · `ice.materials`는 화면이 아직 안 부르거나 안 그려요(HTML 예시 그대로) → 응답으로 확인. 7-1~7-5는 새로고침하면 예시 대화가 보여요.',
        '**아직 안 된 것** — 7-6 · 7-7에는 `stage.changed` 처리가 없어요(새로고침하면 `session.get`으로 이동). 7-7의 아이디어 입력은 브라우저 저장만.',
        '**아직 안 된 것** — 7-3 질문 속 "반응한 카드 요약"과 7-4 힌트 칩은 HTML 고정이에요. 메시지에 `attachments` / `hints` 필드를 두는 것을 제안(명세 미반영, 확인요청 참고).',
        '진행자도 인터뷰 — 세션 시작 시 진행자도 7-1로, 인터뷰가 끝나면 대화창에 7-6 링크 말풍선(`hostLink`) · 7-5는 열 때 진행자면 바로 표시: `assets/js/app.js`(`stageScreen`) · `assets/js/icebreak-chat.js` · `screens/07-5-icebreak-q5-wrapup/screen.js`',
    ],
)
