# 7차 전달 문서 내용 — 9번 파트 나누기 · 추가 질문 · 배치 · 팀장 확정 · 보고서 (화면 9-1 ~ 9-5)
# · 노형원이 만든 "2차(9번)" 전달 문서(ho_docs.team_delivery)를 차수 문서 형식(SPEC)으로 옮긴 것 (2026-09-18 합본)
# · 검사/미리보기: python _generator/check_delivery.py 7   → 문제 0건이 되면 READY = True
READY = True

SPEC = dict(
    phase='7차',
    title='백엔드 7차 전달 — 화면 9-1 ~ 9-5 (파트 나누기 · 겹친 후보 질문 · 배치 초안 · 팀장 확정 · 보고서)',
    intro='주제가 정해진 뒤(8-7) **누가 무엇을 맡을지 정하고 보고서를 만드는** 범위예요. 화면 폴더: `screens/09-1-part-split`, `screens/09-2-overlap-questions`, `screens/09-3-assign-draft`, `screens/09-4-leader-confirm`, `screens/09-5-report` (각 README에 화면 설명). 9번 공통 동작은 `assets/js/team.js`. 발산(8번)을 아직 안 만들었어도 **테스트용 데이터를 DB에 직접 넣어** 이 범위만 따로 만들 수 있어요(아래 "테스트 준비").',
    rules=[
        '**파트는 세 종류** — 결과를 좌우하는 파트(core) · 보통 파트(normal) · 작은 일(small, 스킬 없이 누구나). 주제 확정 직후 AI 작업 11이 확정 주제 · AI 검증 · **이름 없는** 팀 스킬(P1 · P2…)로 파트와 후보를 만들어요.',
        '**후보는 프로필 스킬로** — 한 파트에 후보가 2명 이상이면 "겹침"이라 **그 사람들에게만** 추가 질문 2개(AI 작업 12)를 하고, 1명이면 바로 배정, 없으면 "후보 없음"으로 범위 조정 대안을 제안해요.',
        '**추가 질문의 답은 본인과 AI만** 봐요. 결과는 배치표에 "추가 질문으로 정했어요"라고만 나오고 점수 · 비교 근거는 어떤 응답에도 넣지 않아요(AI 작업 13의 근거는 서버에만).',
        '**분량 맞추기** — 핵심 파트가 한 사람에게 몰려도 괜찮고, 대신 **작은 일**을 다른 사람에게 더 줘서 네 사람의 분량이 비슷하게(계산이지 AI가 아님). 쏠리면 팀장에게 "옮기기 제안"을 줘요.',
        '**팀장** — 주제 확정(8-7 `topic.confirm`) 때 정해지는 참가자 1명(`leaderParticipantId`, 안 보내면 진행자). 배치를 고치고 **확정**하는 사람은 팀장뿐이에요(`팀장만` API를 다른 사람이 부르면 `403 NOT_LEADER`). `session.get`의 `me.isLeader`로 9-3 / 9-4를 가르고요.',
        '**단계는 서버가 넘겨요** — `team.split` → (진행자 "추가 질문 시작") `team.questions` → (모두 답하거나 **5분**이 지나면 **서버가 자동**) `team.assign` → (**팀장의 `team.confirm`으로만**) `report`. 겹친 후보가 없으면 `team.questions`를 건너뛰어요. 파트 나누기 AI가 안 끝났는데 넘기면 `409 PARTS_NOT_READY`.',
        '**보고서** — 배치를 확정하면 AI 작업 15가 A4 2쪽 내용을 만들어요. **PDF는 서버에서 만들지 않아요**(프론트가 브라우저 인쇄로 저장). **공유 링크도 없어요** — 참가자가 앱에서 보거나 PDF로 나눠요. 확정 뒤 팀장이 담당을 고치면 보고서를 다시 만들고 `report.ready`를 다시 보내요. 세션은 확정 시점에 `status: ended`.',
    ],
    rules_after='익명 규칙은 [01-백엔드-한눈에-보기.md](01-백엔드-한눈에-보기.md)의 "5. 익명 규칙"(추가 질문의 답 · 점수는 끝까지 비공개, 이야기해 볼 파트 표시는 팀장에게만), AI 작업 11 · 12 · 13 · 15는 [05-AI-작업-목록.md](05-AI-작업-목록.md), 공통 형식은 [02-API-공통-규칙.md](02-API-공통-규칙.md).',
    api_intro='9-1(parts) → 9-2(questions · answer) → 9-3(assignment · mark) · 9-4 팀장(reassign · suggestion · revert · confirm) → 9-5(report) 순서예요. **이미 있는 API 3개가 바뀌어요**: `topic.confirm`(단계가 `team.split`로 · 요청에 `leaderParticipantId` 선택 · 응답에 `leader`), `session.advance`(9단계 규칙 · `409 PARTS_NOT_READY`), `session.get`(`me.isLeader`). 바뀐 내용은 각 API 상세에 들어 있어요(4차 문서와 겹치는 부분은 이 문서가 우선).',
    ids=['team.parts', 'team.questions', 'team.answer', 'team.assignment', 'team.mark',
         'team.reassign', 'team.suggestion', 'team.revert', 'team.confirm', 'report.get'],
    why={'team.parts': '9-1 파트 · 후보 목록 (AI 파트 나누기가 끝나야 `ready`)', 'team.questions': '9-2 내 추가 질문 (겹친 후보만)', 'team.answer': '9-2 답 제출',
         'team.assignment': '9-3 · 9-4 배치 초안 · 분량', 'team.mark': '9-3 "이야기해 볼 파트" 표시',
         'team.reassign': '9-4 담당 바꾸기 (팀장)', 'team.suggestion': '9-4 옮기기 제안 받기 / 그대로 두기 (팀장)',
         'team.revert': '9-4 AI 초안으로 되돌리기 (팀장)', 'team.confirm': '9-4 확정 → 보고서 (팀장)',
         'report.get': '9-5 A4 2쪽 보고서 · A4 지난 세션 "보고서 보기"'},
    events_intro='7차가 맡는 실시간 이벤트는 아래 4개예요. `stage.changed`(2차)로 9-1 → 9-2 → 9-3/9-4 → 9-5가 이동하고, 팀장이면 `team.assign`에서 9-4로 가요(`App.stageScreen`의 세 번째 인자 `isLeader`). 이벤트에도 익명 규칙이 적용돼요 — 답 · 점수 · 누가 표시했는지는 넣지 않아요.',
    events=['team.parts.ready', 'team.assignment.updated', 'team.confirmed', 'report.ready'],
    done_intro='프론트의 `assets/js/config.js`에서 `useMock: false`, `baseUrl`을 서버 주소로 바꾸고 확인해요. **1차(계정 · 방 입장 · 재접속)와 2차(단계 넘기기 · 실시간)가 끝난 서버** 기준이에요.<br>사람마다 **다른 브라우저 프로필**(또는 다른 브라우저)로 로그인해요 — 같은 프로필의 창끼리는 로그인 정보가 섞여요.<br>모양이 궁금하면 같은 명세로 동작하는 가짜 백엔드가 있어요: `python _tools/test-backend-team.py` → http://127.0.0.1:8768/index.html<br>발산(8번)이 없어도 되게 세션 하나를 아래 "테스트 준비" 상태로 만들어 두고 시작해요. 시나리오의 팀장(L)은 `topic.confirm` 때 정한 참가자, 진행자(H)는 방을 만든 사람이에요.',
    scenarios=[
        ('H가 8-7에서 주제 확정 (`leaderParticipantId` 포함 또는 생략)', '모두 9-1로 이동 · 단계 `team.split` · `topic.confirmed`의 `leader`가 지정한 참가자(생략하면 진행자) · 파트 나누기 AI 작업 시작'),
        ('파트 나누기 AI가 도는 중에 9-1 열기', '`team.parts` 응답 `ready: false` → 안내 문구 · 끝나면 `team.parts.ready` 로 자동 표시'),
        ('AI가 끝난 뒤 9-1 화면', '파트별 필요한 스킬 · 후보(겹침 / 1명 / 후보 없음) · 작은 일 개수 · "내가 후보인 파트" 표시 · 후보 이름은 이 단계부터 공개'),
        ('AI가 안 끝났는데 H가 "추가 질문 시작"(`session.advance` from: team.split)', '409 PARTS_NOT_READY · 단계 그대로'),
        ('H가 "추가 질문 시작"', '단계 `team.questions` · 겹친 후보는 9-2로, 겹치지 않은 사람은 9-1에서 기다림'),
        ('겹친 파트가 하나도 없는 주제', '`team.questions`를 건너뛰고 바로 `team.assign` (9-3 · 팀장 9-4)'),
        ('9-2에서 첫 파트 답 제출(`team.answer`)', '다음 파트 질문으로 바뀜(`nextPartId`) · 빈 답은 400 VALIDATION'),
        ('마지막 파트까지 제출', '"답을 모두 보냈어요" → 9-1에서 기다림'),
        ('**익명**: 다른 후보가 9-2 `team.questions` 응답을 열어봄', '응답 어디에도 **다른 사람 답 · 점수 없음** · 내 질문과 내 답만'),
        ('겹친 후보가 모두 답함', '서버가 **자동으로** `team.assign` 저장 → `stage.changed` → 모두 9-3(팀장은 9-4) · 이후 `team.answer`는 409 STAGE_CLOSED'),
        ('5분이 지났는데 답 안 한 사람이 있음 (`team.questions`의 `remainingSec`이 0)', '답한 것만으로 정하고 `team.assign`으로 · 안 한 사람은 그 파트 후보에서 빠짐 · 이후 답 제출은 409 STAGE_CLOSED'),
        ('9-3 화면 (`team.assignment`)', '파트별 담당 · 정한 방법(추가 질문 / 후보 1명 / 분량 맞추기 / 대안) · 사람별 분량 막대 · 작은 일 배분 · `version`'),
        ('팀원이 파트 표시(`team.mark`)', '팀장 9-4에 "○○ 님이 이야기해 보자고 표시" · `team.assignment.updated` · **다른 팀원의 9-3에는 안 보임**'),
        ('팀장이 담당 바꾸기(`team.reassign`)', '바꾼 줄 표시 + 분량 다시 계산 + 쏠리면 옮기기 제안(`suggestion`) · 모두에게 `team.assignment.updated`(version)'),
        ('"옮기기" / "그대로 둘게요"(`team.suggestion`)', '작은 일이 옮겨짐 / 제안만 닫힘 · 이미 처리한 제안은 409 SUGGESTION_STALE'),
        ('"AI 초안으로 되돌리기"(`team.revert`)', '팀장이 바꾼 담당이 모두 초안으로 (팀원 표시는 남음)'),
        ('팀장이 아닌 사람이 `team.reassign` · `team.suggestion` · `team.revert` · `team.confirm`', '403 NOT_LEADER'),
        ('다른 창에서 배치가 바뀐 뒤 옛 `version`으로 확정', '409 VERSION_MISMATCH → 다시 불러오면 확정됨'),
        ('팀장이 확정(`team.confirm`)', '단계 `report` 저장 → `team.confirmed` + `stage.changed` → 모두 9-5로 · 세션 `status: ended` · 지난 세션 기록(A4)에 보고서 있음 · 다시 확정은 409 ASSIGNMENT_CONFIRMED'),
        ('보고서가 아직 만들어지는 중', '`report.get` 응답 `ready: false` → 안내 · `report.ready` 오면 A4 2쪽 표시'),
        ('9-5 화면', '1쪽(요약 · 현실성 · 투표 · 파트) · 2쪽(워크플로우 4단계 · 내내 하는 일)이 응답 값으로 채워짐 · PDF는 브라우저 인쇄'),
        ('세션이 끝난 뒤 A4 → "보고서 보기"', '9-5에서 그 세션 보고서가 열림(`?sessionId=`)'),
        ('그 세션 참가자가 아닌 회원이 `report.get`', '403 NOT_PARTICIPANT'),
        ('확정 뒤 팀장이 담당을 고침', '보고서가 다시 만들어지고 `report.ready`를 다시 보냄'),
    ],
    extra_sections=[
        ('이미 있는 API 중 바뀐 것 3개', '\n'.join([
            '| 메서드 | 경로 | 무엇이 바뀌나 |',
            '|---|---|---|',
            '| `POST` | `/sessions/{sessionId}/topic` | 단계가 `team.split`로 바뀜 · 요청에 **팀장(`leaderParticipantId`, 선택)** 추가 · 응답과 `topic.confirmed`에 `leader` |',
            '| `POST` | `/sessions/{sessionId}/stage/next` | 9단계 규칙 추가: `team.split` → `team.questions` → (자동) `team.assign` · `team.assign` → `report`는 팀장의 `team.confirm`으로만 · `409 PARTS_NOT_READY` |',
            '| `GET` | `/sessions/{sessionId}` | `me.isLeader` 추가 (팀장이면 9-4, 아니면 9-3) |',
            '',
            '4차 문서의 `topic.confirm` 상세는 이 문서 것으로 갱신됐어요(같은 명세에서 생성).',
        ])),
        ('단계 넘어가는 규칙', '\n'.join([
            '```',
            '8-7 주제 확정 → team.split(9-1) ──진행자 "추가 질문 시작"──▶ team.questions(9-2)',
            '                    │                                              │',
            '                    └─ 겹친 후보가 없으면 바로 ───────────────────▶ team.assign(9-3 · 팀장 9-4)',
            '                       (모두 답하거나 5분이 지나면 서버가 자동으로 넘김)',
            '                                                                   │',
            '                                                  팀장 "확정" ─────▶ report(9-5)',
            '```',
        ])),
        ('AI가 하는 일 (4가지)', '\n'.join([
            '| # | 언제 | 넣는 것 | 나오는 것 |',
            '|---|---|---|---|',
            '| 11 | 주제 확정 직후 | 확정 주제 · AI 검증 · **이름 없는** 팀 스킬(P1 · P2…) | 파트 목록 + 필요한 스킬 + 후보 + 없는 스킬의 대안 |',
            '| 12 | 파트 나누기 끝 | 파트 이름 · 하는 일 | 파트마다 질문 2개 |',
            '| 13 | 답이 다 모이거나 시간 끝 | 같은 파트 후보들의 답(이름 없이) | 누가 맡을지 + **비공개** 근거 |',
            '| 15 | 팀장이 확정할 때 | 투표 · 검증 · 댓글 요약 · 숨은 공통점 · 확정 배치 | 보고서 A4 2쪽 내용(워크플로우 4단계 포함) |',
            '',
            '자세한 내용은 [05-AI-작업-목록.md](05-AI-작업-목록.md) 11 · 12 · 13 · 15번. 14번(분량 맞추기)은 AI가 아니라 계산이에요.',
        ])),
        ('테스트 준비 (발산 단계를 아직 안 만들었어도 되게)', '\n'.join([
            '세션 하나를 아래 상태로 만들어 두면 7차만 따로 테스트할 수 있어요.',
            '',
            '- 참가자 4명(회원 · 프로필 있음), 진행자 1명 포함',
            '- 프로필 스킬 예: 노형원(프론트엔드 · 발표·피칭 · 서비스 기획) · 이세민(프론트엔드 · 웹 디자인 · 발표·피칭) · 김승희(웹 디자인 · PPT 디자인 · 리서치·사용자 조사) · 박상진(백엔드 · 문서 정리)',
            '- 세션 `status: running`, `stage: team.split`, 확정 아이디어 1개, 팀장 참가자 1명',
            '- 투표 결과 · AI 검증은 보고서에 쓰이니 최소한의 값(1위 3표, 2위 2표, 등급 go)만 넣어두면 돼요',
        ])),
        ('확인이 필요한 것', '\n'.join([
            '- **팀장을 누가 정하나** — 지금은 주제 확정(8-7) 때 진행자가 그대로 팀장이에요(`leaderParticipantId`는 준비됐지만 8-7에 고르는 UI가 없음). 디자인 필요.',
            '- 9-1의 진행자용 "추가 질문 시작 →" 버튼 · 9-3의 파트 표시 모드 · 9-4의 담당 고르는 목록 — 디자인이 없어서 프론트가 임시로 넣었어요(목업 모드에서는 숨김).',
            '- **[결정됨 2026-09-18] 추가 질문(9-2) 제한 시간 = 5분** — `team.questions` 단계에 들어간 시각 + 5분. `team.questions` 응답의 `remainingSec`으로 내려주고, 지나면 답한 것만으로 정해요(안 한 사람은 그 파트 후보에서 빠짐).',
            '- **[결정됨 2026-09-18] 보고서 공유 링크는 만들지 않아요** — 9-5의 "링크 복사" 버튼을 없앴고 `report.get` 응답에서 `shareUrl`을 뺐어요. 보고서는 참가자가 9-5 · A4에서 보거나 **PDF로 저장(브라우저 인쇄)** 해서 나눠요.',
        ])),
    ],
    front_title='프론트 쪽 참고 (이미 구현됨)',
    front=[
        '단계 → 화면 이동(팀장이면 9-4, 아니면 9-3) · `session.get`의 `me.isLeader` 저장: `assets/js/app.js` (`stageScreen` · `syncStage`)',
        '9번 공통 표시(파트 표 · 분량 막대 · 후보 칩): `assets/js/team.js` · 화면별 동작: 각 `screens/09-1-part-split/screen.js` ~ `screens/09-5-report/screen.js`',
        '8-7 "N위로 확정하고 파트 나누기 →" → `topic.confirm` → 9-1 · 참가자는 `topic.confirmed`로 9-1: `screens/08-7-vote-result-host/screen.js`',
        'A4 "보고서 보기" → 9-5(`?sessionId=`): `screens/A4-session-history/screen.js`',
        '보고서 크게 보기 팝업 · PDF 저장(브라우저 인쇄) — 공유 링크 버튼은 없음: `screens/09-5-report/screen.js`',
        '디자인이 없어서 임시로 넣은 것(실서버 모드에서만 보임): 9-1 진행자용 "추가 질문 시작" 버튼 · 9-3 파트 표시 모드 · 9-4 담당 고르는 목록',
    ],
)
