# 4차 전달 문서 내용 — 담당: 친구 (친구의 Claude)
# · 이 파일의 SPEC만 채우면 docs/{파일}이 만들어진다 (모양은 _generator/ho_phase1.py = 1차 문서와 같음)
# · 검사/미리보기: python _generator/check_delivery.py 4   → 문제 0건이 되면 READY = True
# · 진짜 생성: python _generator/handoff.py  (READY=True + 검사 통과일 때만 docs/ 에 씀)
# · 문장 규칙: 표 칸(why · scenarios)에는 줄바꿈·| 금지(<br> 사용) · 에러는 "409 STAGE_MISMATCH"처럼 HTTP 번호와 코드를 같이
READY = True

SPEC = dict(
    phase='4차',
    title='백엔드 4차 전달 — 화면 8-1 · 8-3 · 8-4 · 8-6 · 8-7 (발산 기본 · AI 없이 끝까지)',
    intro='이번에 만들 범위와 **끝났다고 볼 수 있는 기준**이에요. 화면 폴더: `screens/08-1-idea-write`, `screens/08-3-idea-board`, `screens/08-4-idea-comments`, `screens/08-6-vote`, `screens/08-6w-vote-wait`(투표 마친 뒤 대기), `screens/08-7-vote-result-host`(진행자 · 참가자 보기 전용) (각 README에 화면 설명). **AI 없이** 아이디어 제출 → 익명 순위표 → 익명 댓글 → 투표 → 결과 · 주제 확정까지 끝까지 돌아가는 게 목표예요. AI 추천(8-2) · AI 검증(8-5) · AI가 모은 아이디어 · 숨은 공통점은 5차예요.',
    rules=[
        '**아이디어 주인은 결과(8-7) 때만, 댓글 작성자·투표자는 끝까지 비공개** — 투표 결과 전에는 `idea.board` · `comment.targets` · `comment.list` · `vote.state` · `vote.candidate` 어디에도 닉네임 · participantId · `source`(AI 추천 여부)를 넣지 않아요. 진행자에게도 마찬가지예요. 응답에서 걸러내는 건 서버 한 곳(직렬화 계층)에서 하고 테스트를 만들어 주세요.',
        '**별칭(팀원 A·B·C·D)과 줄 순서는 세션마다 무작위로 한 번 정해 고정** — 제출 순서·입장 순서와 달라야 해요. `isMe`는 요청한 본인 줄에만 true. 댓글 목록도 작성 시각순으로 주지 않아요(시간으로 사람을 추측하지 못하게).',
        '**전원이 내야 넘어가요 (제출 강제)** — `diverge.write`는 `memberCount` 전원이 `idea.submit`을 해야, `diverge.comment`는 전원이 아쉬운 점 할당량(`concernDone` = `concernTotal`)을 채워야 `session.advance`가 통과해요. 아니면 `409 NOT_ALL_SUBMITTED`(details에 `pendingCount` · `memberCount`). 연결이 끊긴 사람 때문에 막히면 진행자가 `force: true`로 넘길 수 있고, **그때만** 제출 안 한 사람(빈 줄)이 생겨요.',
        '**단계를 떠날 때 마감** — 넘어가면 서버는 단계를 먼저 저장하고 `stage.changed`를 보내요. `diverge.write`를 떠나면 `idea.submit`은 `409 STAGE_CLOSED`, `diverge.comment`를 떠나면 `comment.create`도 `409 STAGE_CLOSED`. `diverge.review`는 4차 서버(AI 없음)에서는 바로 넘어가요 — 5차가 붙으면 검증이 끝나기 전 review → vote는 `409 STAGE_LOCKED`(5차 문서).',
        '**투표 → 결과 전환** — `memberCount`(진행자 포함 · 내보낸 사람 제외) 모두가 `vote.finish`를 하면 서버가 자동으로 단계를 `diverge.result`로 **저장한 뒤** `stage.changed` → `vote.closed`를 보내요. 진행자가 `session.advance`(from: diverge.vote)로 넘겨도 같은 처리(안 마친 사람 표는 저장된 대로 집계). 저장이 이벤트보다 먼저여야 해요 — 8-6w(대기)가 `vote.closed`를 받고 8-7을 열 때 `session.get`이 아직 vote면 8-6으로 튕겨요. 투표를 마친 사람은 8-6w에서 기다리고, `vote.closed`가 오면 **모두** 8-7로 가요(참가자는 보기 전용).',
        '**결과 → 투표는 `vote.revote`로만, 결과 → 파트 나누기는 `topic.confirm`으로만** — 재투표는 단계를 `diverge.vote`로 되돌려 저장하고 후보를 동점 id로만, `maxVotes`를 1로, 모두의 `finished`를 초기화해요. 주제 확정은 단계를 `team.split`로 저장하고 `topic.confirmed`(팀장 포함) + `stage.changed`를 보내요 → 모두 9-1로. 파트 나누기 AI 작업을 이때 시작해요(7차).',
        '**4차 서버는 AI 칸을 비워서 보내요** — `vote.state`의 `candidates[].grade = null` · `aiIdeas = []` · `commonThreads = []`, `vote.candidate`의 `review = null`, `vote.results`의 `ranks[].grade = null` · `aiMerged` 줄 없음 · `insight = null`. `vote.save`는 **지금 `vote.state`에 있는 후보 id만** 받아요(5차에서 AI 아이디어가 후보에 들어오면 자동으로 허용). `idea.submit`의 `source: "ai"` · `recommendationId`는 저장만 하고 검사는 5차에서.',
        '**중복 · 되돌리기** — `idea.submit` · `vote.save`는 전체 목록을 덮어쓰는 PUT이라 여러 번 보내도 결과가 같아요. `vote.finish`를 두 번 부르면 두 번째도 같은 200. 진행자가 `session.back`으로 되돌려도 이미 저장된 아이디어·댓글·표는 지우지 않아요.',
    ],
    rules_after='단계 순서·인원 수 기준은 [01-백엔드-한눈에-보기.md](01-백엔드-한눈에-보기.md)의 "4. 세션 단계", 익명 규칙 표는 같은 문서 "5. 익명 규칙"(⚠️ 4차에서 가장 중요), 공통 형식은 [02-API-공통-규칙.md](02-API-공통-규칙.md), 저장 구조는 [04-데이터-모델.md](04-데이터-모델.md).',
    api_intro='화면 순서대로 8-1(mine · submit) → 8-3(board) → 8-4(targets · list · create) → 8-6(state · candidate · save · finish) → 8-7(results · revote · confirm)이에요. 8-2 · 8-5와 8-6의 AI 부분(`review.get` · `vote.aiIdea` · `vote.thread`)은 **5차**라 여기 없어요. **2차(대기실 · 단계 넘기기 · 실시간)가 끝난 서버** 위에 얹는 범위이고, 3차(아이스브레이킹) 없이도 테스트할 수 있어요(진행자가 `icebreak`에서 바로 넘기면 됨).',
    ids=[
        'idea.mine',
        'idea.submit',
        'idea.board',
        'comment.targets',
        'comment.list',
        'comment.create',
        'vote.state',
        'vote.candidate',
        'vote.save',
        'vote.finish',
        'vote.results',
        'vote.revote',
        'topic.confirm',
    ],
    why={
        'idea.mine': '8-1 새로고침 · 재접속 때 칸 채우기 (실서버 모드에서 부름)',
        'idea.submit': '8-1 "이 순서로 제출"',
        'idea.board': '8-3 익명 순위표 (실서버 모드에서 표를 다시 그림)',
        'comment.targets': '8-4 왼쪽 목록 + 할당량 (화면이 이 응답으로 그림)',
        'comment.list': '8-4 목록 누르면 먼저 남겨진 댓글',
        'comment.create': '8-4 "댓글 저장"',
        'vote.state': '8-6 후보 · AI 아이디어 · 숨은 공통점 목록 + 내 표 · 8-6w 대기 화면의 `finished` · 인원',
        'vote.candidate': '8-6 목록 누르면 원래 내용 · 댓글 다시 보기',
        'vote.save': '8-6 체크박스 · "이 아이디어에 투표"',
        'vote.finish': '8-6 "투표 마치기"',
        'vote.results': '8-7 결과 줄 다시 그리기 · 아이디어 주인 공개 (참가자도 같은 화면 · 버튼 숨김)',
        'vote.revote': '8-7 "동점만 다시 투표"',
        'topic.confirm': '8-7 "N위로 확정하고 역할 정하기"',
    },
    events_intro='4차가 맡는 실시간 이벤트는 아래 5개예요(전부 인원 수 또는 id만 — 누가 냈는지 · 누가 투표했는지는 넣지 않아요). `stage.changed`(2차)로 8-1 → 8-3 → 8-4 → 8-5 → 8-6이 자동 이동하고, 8-6w · 8-7은 `vote.closed` · `stage.changed`(`diverge.result` · 재투표 `diverge.vote`)로 움직여요. 8-6에는 `stage.changed` 처리가 없어서 새로고침 때 `session.get`으로 이동해요.',
    events=[
        ('ideas.submitted', '8-1 · 8-2에 처리 코드가 아직 없음 → 이벤트 payload로 확인'),
        ('comments.progress', '8-4에 처리 코드가 아직 없음 → 이벤트 payload로 확인'),
        ('vote.progress', '8-6 아래 "투표한 사람 n / m" · 8-6w "현재 n / m명 투표 완료" 갱신'),
        ('vote.closed', '8-6 · 8-6w에 있는 **모두** 8-7로 이동 (참가자는 보기 전용)'),
        ('topic.confirmed', '진행자는 버튼 응답으로, 참가자는 이 이벤트로 9-1(파트 나누기)로 이동'),
    ],
    done_intro='프론트의 `assets/js/config.js`에서 `useMock: false`, `baseUrl`을 서버 주소로 바꾸고 확인해요. **2차(대기실 · 단계 넘기기 · 실시간)가 끝난 서버** 기준이에요.<br>사람마다 **다른 브라우저 프로필**(또는 다른 브라우저)로 로그인해요 — 같은 프로필의 창끼리는 로그인 정보가 섞여요.<br>화면에 아직 버튼이 없거나 서버 데이터를 아직 그리지 않는 동작은, 그 사람 창의 개발자도구 **콘솔에서 `await api.call(…)`** 로 부르거나 **Network 탭의 응답**으로 확인해요.<br>진행자 1명 + 참가자 3명(4명)으로 세션을 시작하고 진행자 콘솔에서 `await api.call(\'session.advance\', {}, { from: \'icebreak\' })`로 `diverge.write`까지 넘긴 뒤 시작해요. 이후 넘기기는 진행자 하단 막대(T2)의 "다음 단계 →"로 해요(콘솔도 됨). 8-4 · 8-6의 왼쪽 목록은 아직 화면 id가 가짜(`ide_0`…)라 **진짜 id는 `idea.board` · `vote.state` 응답에서** 가져와 콘솔로 불러요.',
    scenarios=[
        ('참가자가 8-1에 아이디어 1~3개를 적고 "이 순서로 제출"', '`idea.submit` 200 `submitted: true` · `submittedCount`/`memberCount` · 토스트 "제출했어요. 모두 내면 순위표가 열려요" · 8-3으로 갔다가 단계가 아직 write라 8-1로 돌아옴(정상) · 세션 전원에게 `ideas.submitted`(인원 수만)'),
        ('빈 칸만 두고 제출 / 콘솔에서 4개 · 빈 문장 · 순위 중복으로 `idea.submit`', '프론트는 "아이디어를 1개 이상 적어주세요"로 막음 · 서버는 400 VALIDATION(message에 이유)'),
        ('같은 사람이 내용을 바꿔 다시 제출', '덮어쓰기(PUT) · `submittedCount`는 그대로 · `idea.mine`에 새 내용 · `submitted: true`'),
        ('8-1 새로고침', '`idea.mine`으로 저장된 아이디어가 칸에 채워짐 (제출 전이면 `submitted: false` · HTML 예시 문장이 남아 있을 수 있음 → 아직 안 된 것 참고)'),
        ('아직 안 낸 사람이 있을 때 진행자 하단 막대 "다음 단계 →"(T2)', '`session.advance` 409 NOT_ALL_SUBMITTED · details `pendingCount` → 확인 창 "아직 N명이 제출하지 않았어요" · "기다리기"면 단계 그대로 · 8-1의 아무도 안 움직임'),
        ('전원 제출 뒤 "다음 단계 →" (막대에 "제출 4 / 4명")', '단계 `diverge.board` 저장 → `stage.changed` → 8-1의 모두가 8-3으로 · 이후 `idea.submit`은 409 STAGE_CLOSED 토스트'),
        ('한 명이 연결을 끊은 채 확인 창에서 "그냥 넘기기"', '`session.advance`(force: true)로 넘어감 · 8-3에서 그 사람 별칭 줄만 칸이 비어 있음 · force 없이 보내면 여전히 409 NOT_ALL_SUBMITTED'),
        ('8-3 열기', '`idea.board`로 표가 다시 그려짐 — 팀원 A~D 별칭, 내 줄에 "나" 표시, 위에 "m명 모두 제출했어요"(force로 넘긴 경우만 "n / m명 제출" + 빈 줄)'),
        ('**익명**: 진행자 계정으로 `idea.board`', '응답에 nickname · participantId · `source` 없음 · 별칭↔사람 연결 없음 · 줄 순서가 제출 순서·입장 순서와 다름 · 새로고침해도 같은 별칭·같은 순서'),
        ('**익명**: 참가자 두 명이 각자 `idea.board`', '각자 자기 줄에만 `isMe: true` · 두 사람이 보는 별칭 배치는 같음'),
        ('진행자 `session.advance`(from: diverge.board)', '단계 `diverge.comment` → 8-3의 모두가 8-4로'),
        ('8-4에서 콘솔 `comment.targets`', '`groups`에 내 아이디어 그룹 없음 · `quota.concernTotal` = 다른 사람 아이디어 수(4명이 3개씩이면 9) · 별칭·순위·제목·`status`만'),
        ('8-4 왼쪽 목록 누르기 → 진짜 ideaId로 콘솔 `comment.list`', '화면 목록은 가짜 id라 `comment.list`가 실패(토스트 없이 콘솔) · 진짜 id로 부르면 `idea`(별칭·순위·원문) · `counts` · `items` · `mine`'),
        ('콘솔 `comment.create`(진짜 id, 아쉬운 점만)', '201 `saved: true` · `quota.concernDone` +1 · 다른 사람이 `comment.list`하면 `items`에 보임(작성자 없음)'),
        ('아쉬운 점을 비우고 저장 / 내 아이디어에 댓글 / 좋은 점 3번째', '프론트 토스트 "아쉬운 점은 꼭 적어주세요"(콘솔로 보내면 400 VALIDATION) · 403 OWN_IDEA · 409 PRAISE_LIMIT(`praiseUsed` 2/2)'),
        ('같은 아이디어에 두 번 저장', '수정(댓글은 1개 유지) · `comment.list`의 `mine`에 내 것 · 좋은 점을 지우고 저장하면 `praiseUsed`가 줄어듦'),
        ('**익명**: 두 사람이 차례로 댓글을 쓴 뒤 `comment.list`', '`items`에 작성자 · participantId · 시각 없음 · 순서가 작성 순이 아님(유형순 또는 무작위) · `mine`은 내 것만'),
        ('한 사람이 아쉬운 점 할당량을 다 채움', '진행자에게 `comments.progress`(`doneCount` · `memberCount`) — 8-4 화면 처리 없음 → payload로 확인'),
        ('아쉬운 점을 다 안 쓴 사람이 있을 때 진행자 `session.advance`(from: diverge.comment)', '409 NOT_ALL_SUBMITTED · `comment.targets`의 `quota`로 누가 남았는지는 본인만 알고 진행자에게는 인원 수만'),
        ('전원이 할당량을 채운 뒤 `session.advance`(from: diverge.comment) → 다시 (from: diverge.review)', '단계 `diverge.review` → 8-4의 모두가 8-5로(4차는 예시 화면 그대로 · 목록 클릭은 확인 안 함) · 이후 `comment.create`는 409 STAGE_CLOSED · 다시 넘기면 `diverge.vote` → 모두 8-6으로'),
        ('8-6에서 콘솔 `vote.state`', '`candidates`에 제출된 아이디어 전부(`grade: null` · `isMine`은 내 것만 true · 주인 없음) · `aiIdeas: []` · `commonThreads: []` · `maxVotes: 2` · `myVotes` · `finished`'),
        ('콘솔 `vote.save` — 진짜 id 2개 / 3개 / 후보가 아닌 id', '`myVotes` 2개 · `remaining: 0` / 409 VOTE_LIMIT / 400 NOT_A_CANDIDATE (화면 체크박스는 가짜 id라 에러 토스트 후 체크가 되돌아감 — 정상)'),
        ('콘솔 `vote.candidate`(진짜 id)', '별칭 · 순위 · `originalText` · `comments`(작성자 없음) · `votedByMe` · `review: null` · 주인 없음'),
        ('"투표 마치기"', '`vote.finish` → 토스트 "투표를 마쳤어요 · n / m명" → **8-6w 대기 화면**("현재 n / m명 투표 완료") · 이후 `vote.save`는 409 VOTE_FINISHED · 다른 사람 8-6 아래 "투표한 사람 n / m"과 8-6w 인원이 `vote.progress`로 갱신'),
        ('8-6w에서 새로고침 / 아직 안 마친 사람이 8-6w 주소로 들어옴', '`vote.state`의 `finished`가 true면 인원만 다시 그림 · false면 8-6으로 돌려보냄'),
        ('모두 마치기 (또는 진행자 `session.advance` from: diverge.vote)', '서버가 단계 `diverge.result` 저장 → `stage.changed` → `vote.closed` → 8-6w · 8-6에 있는 **모두** 8-7로 이동하고 튕기지 않음 · 안 마친 사람 표는 저장된 대로 집계'),
        ('투표 중에 `vote.results`', '409 VOTE_NOT_CLOSED'),
        ('8-7 열기', '`vote.results`로 줄이 다시 그려짐 — 표 수 순, **주인 닉네임·순위가 처음 공개**, "표를 받지 못한 아이디어 N개…" 문구, 첫 줄 라디오 켜짐 (등급 칸은 4차에서 `grade: null`이라 "undefined"로 보임 — 확인 안 함)'),
        ('**익명(결과 후)**: `vote.results` · `vote.candidate` · `comment.list` · `idea.board`', '누가 어디에 투표했는지 · 댓글 작성자는 어디에도 없음 · `idea.board` · `comment.list` · `vote.candidate`는 결과 후에도 주인 없음 그대로 · `source`(AI 추천 여부)는 결과에도 없음'),
        ('참가자가 8-7을 열기', '같은 결과 목록(주인 공개) · 라디오 · "확정" · "동점만 다시 투표" 버튼이 **숨겨짐** · 안내 "진행자가 주제를 확정하면 함께 넘어가요" · 콘솔로 `topic.confirm` · `vote.revote`를 부르면 403 FORBIDDEN'),
        ('진행자 "동점만 다시 투표" (화면의 3위 줄들로 계산)', '`vote.revote` → 단계 `diverge.vote` 저장 → `stage.changed` → `vote.state`의 후보가 그 id들만 · `maxVotes: 1` · 모두 `finished: false` · 8-7 · 8-6w에 있던 모두가 8-6으로 돌아감 · 다시 모두 마치면 결과에서 동점 후보의 표만 재투표 표로 바뀌고 나머지 순위는 그대로'),
        ('진행자가 다른 줄을 고르고 "N위로 확정"', '`topic.confirm` → `topic.confirmed` + `stage.changed` · 단계 `team.split` 저장 · 진행자 토스트 "…(으)로 확정했어요" → 9-1 · 참가자 8-7은 `topic.confirmed`로 토스트 "주제가 …(으)로 확정됐어요" → 9-1 · 다시 확정/재투표는 409 STAGE_LOCKED · 결과에 없는 id는 404 NOT_FOUND'),
    ],
    extra_sections=[
        ('이번 범위의 경계', '\n'.join([
            '- **5차**: AI 추천(8-2 `idea.recommend`) · AI 검증(8-5 `review.list` · `review.get`) · AI가 모은 아이디어 · 숨은 공통점(8-6 `vote.aiIdea` · `vote.thread` · `vote.threadReact`) · 결과 인사이트 카드. 4차 서버는 이 자리를 `null` · `[]`로 비워서 보내요.',
            '- **8-5 화면은 4차 완료 기준에 없어요** — 목록을 누르면 `review.get`이 없어서 실패해요(토스트 없이 콘솔에만 에러). 진행자가 comment → review → vote로 그냥 넘기면 돼요.',
            '- 주제 확정 뒤(파트 나누기 · 추가 질문 · 배치 · 보고서, 화면 9-1 ~ 9-5)는 **7차**예요. `topic.confirm`의 `leaderParticipantId`(팀장, 선택)와 응답의 `leader`는 7차 문서에 자세히.',
            '- 단계 넘기기 · 되돌리기 · WebSocket 자체는 **2차**예요. 4차는 단계에 들어가고 나갈 때 할 일(전원 제출 확인 · 마감 · 투표 종료 · 재투표 · 확정)만 맡아요. `409 NOT_ALL_SUBMITTED`의 판단(누가 냈는지 세기)은 4차가, 에러를 돌려주는 자리는 2차의 `session.advance`예요.',
        ])),
        ('확인이 필요한 것', '\n'.join([
            '자세한 내용과 제안은 `_작업메모/친구-확인요청.md`에 있어요. 이 문서는 제안대로 쓴 상태예요.',
            '',
            '1. **[프론트] 8-4 · 8-6 왼쪽 목록이 가짜 id** — `comment.targets` · `vote.state`를 아직 안 그려서 목록을 누르면 실패해요(토스트 없음). 그래서 댓글 저장 · 표 저장은 콘솔로 확인해요.',
            '2. **[명세] `vote.finish` · `vote.revote` · `topic.confirm`에 에러가 없음** — 투표 단계가 아닐 때 `vote.save` · `vote.finish`는 409 STAGE_CLOSED, `vote.finish` 두 번째는 같은 200, 결과 단계가 아닌데 `vote.revote` · `topic.confirm`은 409 STAGE_LOCKED, 결과에 없는 id는 404 NOT_FOUND로 썼어요.',
            '3. **[명세] 재투표 뒤 결과 합산** — 동점 후보의 표만 재투표 표로 바꾸고 나머지 순위는 그대로 두는 것으로 썼어요. 재투표에서도 동점이면 다시 열 수 있어요.',
            '4. **[명세] 댓글 수정 때 좋은 점 할당량** — 좋은 점을 지우고 다시 저장하면 `praiseUsed`가 줄어드는 것으로 썼어요.',
            '5. **[결정됨 2026-09-18] 제출 강제** — 전원이 내야 넘어가고(409 NOT_ALL_SUBMITTED), 진행자가 `force: true`로 넘긴 경우에만 빈 줄(별칭 줄은 있고 칸이 빔)이 생겨요.',
            '6. **[결정됨 2026-09-18] 8-6w 대기 화면 · 참가자용 8-7** — 대기실(6)과 같은 틀의 8-6w를 추가했고, 8-7은 같은 화면에서 참가자면 버튼을 숨겨요. 새 API는 없어요.',
            '7. **[프론트] 8-7 등급 칸** — `grade: null`이면 "undefined"가 보여요(5차 전까지). 4차 완료 기준에서는 확인하지 않아요.',
        ])),
    ],
    front_title='프론트 쪽 참고 (이미 구현된 것 · 아직 안 된 것)',
    front=[
        '8-1 — 실서버 모드에서 `idea.mine`으로 칸 채우기 · 빈 칸 빼고 1~3개 `idea.submit` → 8-3(단계가 write면 `session.get`으로 8-1 복귀) · `stage.changed`가 `diverge.board`면 8-3: `screens/08-1-idea-write/screen.js`',
        '8-3 — `idea.board`로 표 다시 그리기(내 줄 "나", 위 "n / m명 제출") · `stage.changed`가 `diverge.comment`면 8-4: `screens/08-3-idea-board/screen.js`',
        '8-4 — 목록 선택 시 `comment.list` · "댓글 저장" → `comment.create`(아쉬운 점 필수 검사) · 응답 `quota`로 "4 / 9 · 1 / 2" 갱신 · `stage.changed`가 `diverge.review`면 8-5: `screens/08-4-idea-comments/screen.js`',
        '8-6 — 체크/투표 버튼 → `vote.save`(체크한 id 전체, 2표 제한은 화면에서도 검사) · "투표 마치기" → `vote.finish` 토스트 → 8-6w · 열 때 `vote.state`가 `finished`면 바로 8-6w · `vote.progress`로 "투표한 사람 n / m" · `vote.closed`면 모두 8-7: `screens/08-6-vote/screen.js`',
        '8-6w — 열 때 `vote.state`(안 마쳤으면 8-6으로) · `vote.progress`로 인원 · `vote.closed` 또는 `stage.changed`(result)면 8-7 · 재투표(`diverge.vote`)면 8-6: `screens/08-6w-vote-wait/screen.js`',
        '8-7 — `vote.results`로 결과 줄 다시 그리기(주인 공개 · 첫 줄 선택) · 줄 선택 → 버튼 "N위로 확정" · `topic.confirm` · "동점만 다시 투표" → 화면의 3위 줄로 `vote.revote`(서버 `ties` 아님) · 참가자면 라디오 · 버튼 숨김(`applyRole`) · `topic.confirmed` 토스트 · 재투표 `stage.changed`면 8-6: `screens/08-7-vote-result-host/screen.js`',
        '세션 화면 공통 — 열릴 때 `session.get`으로 단계 확인 후 다른 단계면 이동(그래서 버튼으로 먼저 이동해도 단계가 안 바뀌었으면 돌아옴), 401이면 refresh 후 재시도, 에러는 `message`를 토스트로: `assets/js/app.js` · `assets/js/api.js`',
        '**아직 안 된 것** — 8-4의 `comment.targets`, 8-6의 `vote.state`는 안 그려요. 왼쪽 목록은 HTML 예시이고 id도 가짜(`ide_0`…)라 목록을 누르면 실패(토스트 없이 콘솔) → 진짜 id는 응답에서 가져와 콘솔로.',
        '**아직 안 된 것** — 8-1은 HTML 예시 아이디어 2개가 칸에 남아 있어서 지우지 않고 제출하면 예시 문장이 제출돼요. 8-x 진행자 화면에는 단계 넘기기 버튼이 없어요(콘솔 `session.advance`).',
        '진행자 하단 막대(T2) — 8-1 ~ 8-6에서 진행자에게만 "제출 n / m명 · 다음 단계 →" · `ideas.submitted` · `comments.progress` · `vote.progress`로 숫자 갱신 · 409 NOT_ALL_SUBMITTED면 확인 창 → `force`: `assets/js/app.js` (`hostBar`)',
        '시간 종료 안내 창(T1) — 타이머가 00:00이면 모든 세션 화면에서 · 진행자는 `session.extend` / 이대로 계속: `assets/js/app.js` (`timeUp`)',
        '**아직 안 된 것** — 8-7 재투표 후보는 서버 `ties`가 아니라 화면의 3위 줄로 계산하고, 등급 칸은 `grade: null`이면 "undefined"로 보여요.',
    ],
)
